### ISSUE TITLE
Try installing Reflexjs recipe

### ISSUE THREAD

**Issue by jcze91** [blitz-js/blitz#1723] opened 2021-01-15 16:12 UTC
### What is the problem?

Hello, I had multiple Typescript error while trying to install Reflexjs recipe, here are the logs

### Steps to Reproduce

1. blitz new app
2. cd app
3. blitz install reflexjs

### Versions

0.29.2

### Other

`TSError: ⨯ Unable to compile TypeScript:
    ../../../../JF0FE~1.CAZ/AppData/Local/Temp/blitz-recipe-blitz-js-blitz/index.ts:1:47 - error TS2307: Cannot find module '@blitzjs/installer' or its corresponding type
    declarations.

    1 import {addImport, paths, RecipeBuilder} from "@blitzjs/installer"
                                                    ~~~~~~~~~~~~~~~~~~~~
    ../../../../JF0FE~1.CAZ/AppData/Local/Temp/blitz-recipe-blitz-js-blitz/index.ts:2:24 - error TS2307: Cannot find module 'ast-types/lib/node-path' or its corresponding type
    declarations.

    2 import {NodePath} from "ast-types/lib/node-path"
                             ~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../../../JF0FE~1.CAZ/AppData/Local/Temp/blitz-recipe-blitz-js-blitz/index.ts:3:15 - error TS2307: Cannot find module 'jscodeshift' or its corresponding type declarations.

    3 import j from "jscodeshift"
                    ~~~~~~~~~~~~~
    ../../../../JF0FE~1.CAZ/AppData/Local/Temp/blitz-recipe-blitz-js-blitz/index.ts:4:26 - error TS2307: Cannot find module 'jscodeshift/src/Collection' or its corresponding type
    declarations.

    4 import {Collection} from "jscodeshift/src/Collection"
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

Thanks for your help :)

**Comment by flybayer** [comment] 2021-01-15 19:43
What is the output of `blitz -vV` (this was requested in the issue template :)

**Comment by MrLeebo** [comment] 2021-01-22 20:46
@jcze91 I followed the repro steps using version 0.29.2 but couldn't reproduce the errors, it ran successfully.

If this output was from your VS Code or another IDE, perhaps restarting the TS Server would clear it up? I'm closing this issue for now, but if you are still experiencing issues, please reopen with the version information that Brandon requested.

**Closed by MrLeebo** 2021-01-22 20:46 UTC
Labels: status/triage
