### ISSUE TITLE
No native build was found for platform=linux arch=x64 runtime=node abi=108 uv=1 libc=glibc node=18.19.0 webpack=true

### ISSUE THREAD

**Issue by MartinMuzatko** [blitz-js/blitz#4374] opened 2024-09-11 23:29 UTC
### What is the problem?

When I build and start a fresh project and then click on signup or login, I get the following error.
I suppose the prisma client is meant with this message?

### Paste all your error logs here:

```
{"0":"getCurrentUser()","1":"Finished: resolver:3ms serializer:0ms total:3ms","_meta":{"runtime":"Nodejs","runtimeVersion":"v18.19.0","hostname":"MisanDesktop","name":"blitz-invoke","date":"2024-09-11T18:55:01.131Z","logLevelId":3,"logLevelName":"INFO","path":{"fullFilePath":"/home/misan/dev/gitlab/ssf-blitz3/.next/server/chunks/204.js:116:77116","fileName":"204.js","fileNameWithLine":"204.js:116","fileColumn":"77116","fileLine":"116","filePath":"/.next/server/chunks/204.js","filePathWithLine":"/.next/server/chunks/204.js:116","method":"v.postResponse"}}}
 ⨯ Error: No native build was found for platform=linux arch=x64 runtime=node abi=108 uv=1 libc=glibc node=18.19.0 webpack=true
    loaded from: /home/misan/dev/gitlab/ssf-blitz3/.next/server/app/api/rpc/[[...blitz]]

    at _.resolve._.path (/home/misan/dev/gitlab/ssf-blitz3/.next/server/app/api/rpc/[[...blitz]]/route.js:1:10162)
    at _ (/home/misan/dev/gitlab/ssf-blitz3/.next/server/app/api/rpc/[[...blitz]]/route.js:1:8464)
    at 10723 (/home/misan/dev/gitlab/ssf-blitz3/.next/server/app/api/rpc/[[...blitz]]/route.js:1:14570)
    at t (/home/misan/dev/gitlab/ssf-blitz3/.next/server/webpack-runtime.js:1:143)
    at 59909 (/home/misan/dev/gitlab/ssf-blitz3/.next/server/app/api/rpc/[[...blitz]]/route.js:1:10759)
    at t (/home/misan/dev/gitlab/ssf-blitz3/.next/server/webpack-runtime.js:1:143)
    at 14604 (/home/misan/dev/gitlab/ssf-blitz3/.next/server/app/api/rpc/[[...blitz]]/route.js:1:68617)
    at t (/home/misan/dev/gitlab/ssf-blitz3/.next/server/webpack-runtime.js:1:143)
    at 82640 (/home/misan/dev/gitlab/ssf-blitz3/.next/server/app/api/rpc/[[...blitz]]/route.js:1:6697)
    at t (/home/misan/dev/gitlab/ssf-blitz3/.next/server/webpack-runtime.js:1:143)
```

### Paste all relevant code snippets here:

```
not relevant
```

### What are detailed steps to reproduce this?

1.blitz new example-project
2. cd example-project
3. npm run build
4. npm run start
5. click on login and attempt to login with any credentials

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.1.1 (global)
Blitz version: 2.1.1 (local)
Linux 5.15 | linux-x64 | Node: v18.19.0


 Package manager: npm

  System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (4) x64 AMD Ryzen 7 3800X 8-Core Processor
    Memory: 4.97 GB / 5.79 GB
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.4 - /mnt/c/Users/marti/AppData/Roaming/npm/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.1.1 => 2.1.1
    @blitzjs/next: 2.1.1 => 2.1.1
    @blitzjs/rpc: 2.1.1 => 2.1.1
    @prisma/client: 5.4.2 => 5.4.2
    blitz: 2.1.1 => 2.1.1
    next: 14.1.4 => 14.1.4
    prisma: 5.4.2 => 5.4.2
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.8.4 => 4.9.5
```

### Please include below any other applicable logs and screenshots that show your problem:

![image](https://github.com/user-attachments/assets/f25f61fc-241b-4b5d-9187-2c084a7ca70a)

**Comment by MykhailoShavlovskyi** [comment] 2024-09-19 18:24
Happens for me on my mac machine and on a project on AWS deployed via flightcontrol. I am using latest version of blitz.

**Comment by micha2it** [comment] 2024-09-20 11:40
A workaround is to delete `app/api/rpc/[[...blitz]]/route.ts`. And create a `pages/api/rpc/[[...blitz]].ts`:

```
import { rpcHandler } from "@blitzjs/rpc"
import { api } from "src/app/blitz-server"

export default api(rpcHandler({ onError: (error, ctx) => console.log(error) }))
```

**Comment by cbovard** [comment] 2024-09-22 18:04
> import { rpcHandler } from "@blitzjs/rpc"
> import { api } from "src/app/blitz-server"
> 
> export default api(rpcHandler({ onError: (error, ctx) => console.log(error) }))

I have tested this on a new Blitz app and it worked. 
I did a blitz build then a blitz start. Tested login, logout and new account.
I also tested running blitz dev and it worked also.

Just have to move a few files around to get it working. Ideally be great if we did not have to do this but. It works.
If there is a way I can help let me know.

**Comment by gengjiawen** [comment] 2024-10-05 15:14
duplicate of https://github.com/blitz-js/blitz/issues/4354

**Closed** 2024-10-08 14:10 UTC
Labels: kind/bug, status/triage
