### ISSUE TITLE
5 Styled JSX related eslint errors on new unmodified project

### ISSUE THREAD

**Issue by DominicTobias** [blitz-js/blitz#3903] opened 2022-10-15 22:22 UTC
### What is the problem?

Running `lint` results in 5 eslint errors on a new unmodified project.

### Paste all your error logs here:

```
% pnpm lint

> eslint --ignore-path .gitignore --ext .js,.ts,.tsx .


<project>/app/core/components/Form.tsx
  48:18  error  Unknown property 'global' found  react/no-unknown-property
  48:25  error  Unknown property 'jsx' found     react/no-unknown-property

<project>/app/core/components/LabeledTextField.tsx
  45:16  error  Unknown property 'jsx' found  react/no-unknown-property

<project>/pages/index.tsx
  137:16  error  Unknown property 'jsx' found     react/no-unknown-property
  137:20  error  Unknown property 'global' found  react/no-unknown-property

✖ 5 problems (5 errors, 0 warnings)
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. blitz new myAppName (Typescript, PNPM, final-form)
3. cd myAppName
4. pnpm/yarn/npm lint

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.12 (global)
Blitz version: 2.0.0-beta.12 (local)
macOS Monterey | darwin-arm64 | Node: v18.10.0


 Package manager: pnpm

  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 6.42 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.10.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.12 => 2.0.0-beta.12
    @blitzjs/next: 2.0.0-beta.12 => 2.0.0-beta.12
    @blitzjs/rpc: 2.0.0-beta.12 => 2.0.0-beta.12
    @prisma/client: 4.0.0 => 4.0.0
    blitz: 2.0.0-beta.12 => 2.0.0-beta.12
    next: 12.2.5 => 12.2.5
    prisma: 4.0.0 => 4.0.0
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.5.3 => 4.8.4
```

**Comment by beerose** [comment] 2022-10-17 10:28
Closing as a duplicate of https://github.com/blitz-js/blitz/issues/3814

We're currently investigating it.

**Closed by beerose** 2022-10-17 10:28 UTC
Labels: kind/bug, status/triage
