### ISSUE TITLE
pnpm does not install dependencies correctly

### ISSUE THREAD

**Issue by chronark** [blitz-js/blitz#2465] opened 2021-06-09 07:34 UTC
### What is the problem?

This might not actually blitz's fault but I think submitting this issue is still the right thing.

When I try to install dependencies via pnpm (v6.7.3) there seems to be something going wrong.
The install command succeeds but if I run the dev server I get this runtime error: 
![image](https://user-images.githubusercontent.com/18246773/121311563-d37a6c80-c904-11eb-952f-c7cb22c0cb64.png)

And when trying to build it fails with type errors (see below)

## pnpm run build
```bash
 chronark@pop-os  ~/github/chronark/blitzWithPnpm   master  npx blitz new blitz-pnpm
cd blitz-pnpm
rm -rf node_modules yarn.lock
pnpm install

pnpm run build
✔ Pick a form library (you can switch to something else later if you want) · React Final Form

Hang tight while we set up your new Blitz app!

CREATE    .env
CREATE    .env.local
CREATE    .env.test.local
CREATE    .eslintrc.js
CREATE    README.md
CREATE    app/auth/components/LoginForm.tsx
CREATE    app/auth/components/SignupForm.tsx
CREATE    app/auth/mutations/changePassword.ts
CREATE    app/auth/mutations/forgotPassword.test.ts
CREATE    app/auth/mutations/forgotPassword.ts
CREATE    app/auth/mutations/login.ts
CREATE    app/auth/mutations/logout.ts
CREATE    app/auth/mutations/resetPassword.test.ts
CREATE    app/auth/mutations/resetPassword.ts
CREATE    app/auth/mutations/signup.ts
CREATE    app/auth/pages/forgot-password.tsx
CREATE    app/auth/pages/login.tsx
CREATE    app/auth/pages/reset-password.tsx
CREATE    app/auth/pages/signup.tsx
CREATE    app/auth/validations.ts
CREATE    app/core/components/Form.tsx
CREATE    app/core/components/LabeledTextField.tsx
CREATE    app/core/hooks/useCurrentUser.ts
CREATE    app/core/layouts/Layout.tsx
CREATE    app/pages/404.tsx
CREATE    app/pages/_app.tsx
CREATE    app/pages/_document.tsx
CREATE    app/pages/index.test.tsx
CREATE    app/pages/index.tsx
CREATE    app/users/queries/getCurrentUser.ts
CREATE    babel.config.js
CREATE    blitz.config.ts
CREATE    db/index.ts
CREATE    db/schema.prisma
CREATE    db/seeds.ts
CREATE    global.d.ts
CREATE    jest.config.js
CREATE    mailers/forgotPasswordMailer.ts
CREATE    package.json
CREATE    public/favicon.ico
CREATE    public/logo.png
CREATE    test/setup.ts
CREATE    test/utils.tsx
CREATE    tsconfig.json
CREATE    types.ts

✔ Retrieving the freshest of dependencies
✔ Resolving packages
✔ Fetching packages
✔ Linking dependencies
✔ Building fresh packages
✔ Initializing SQLite database
✔ Committing your app

Your new Blitz app is ready! Next steps:

   1. cd blitz-pnpm
   2. blitz dev

 WARN  blitz > @blitzjs/babel-preset: babel-plugin-superjson-next@0.3.0 requires a peer of next@>=9.0.0 but version 10.2.3-0.37.0 was installed.
 WARN  blitz > @blitzjs/core > @blitzjs/next: @next/react-dev-overlay@10.2.3 requires a peer of react@^16.9.0 || ^17 but version 0.0.0-experimental-0eea57724 was installed.
 WARN  blitz > @blitzjs/core > @blitzjs/next: @next/react-dev-overlay@10.2.3 requires a peer of react-dom@^16.9.0 || ^17 but version 0.0.0-experimental-0eea57724 was installed.
 WARN  blitz > @blitzjs/core > @blitzjs/next: null-loader@4.0.1 requires a peer of webpack@^4.0.0 || ^5.0.0 but none was installed.
 WARN  blitz > @blitzjs/core > @blitzjs/next: styled-jsx@3.3.2 requires a peer of react@15.x.x || 16.x.x || 17.x.x but version 0.0.0-experimental-0eea57724 was installed.
 WARN  11 other warnings
Packages: +1312
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/chronark/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 1307, reused 1307, downloaded 0, added 1312, done
node_modules/.pnpm/@prisma+engines@2.19.0-39.c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d/node_modules/@prisma/engines: Running postinstall script...
node_modules/.pnpm/@prisma+engines@2.19.0-39.c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d/node_modules/@prisma/engines: Running postinstall script, done in 335ms0/node_modules/core-js-pure: Running postinstall script, done in 104ms
node_modules/.pnpm/core-js@3.14.0/node_modules/core-js: Running postinstall script, done in 102ms/@prisma/engines: Runninode_modules/.pnpm/@prisma+engines@2.24.1-2.18095475d5ee64536e2f93995e48ad800737a9e4/node_modules/@prisma/engines: Running postinstall script, done in 415msode_modules/esbuild: Running postinstall script, done in 160ms
node_modules/.pnpm/sodium-native@3.2.1/node_modules/sodium-native: Running install script, done in 107ms
node_modules/.pnpm/prisma@2.24.1/node_modules/prisma: Running preinstall script, done in 51ms
node_modules/.pnpm/prisma@2.24.1/node_modules/prisma: Running install script, done in 52ms
node_modules/.pnpm/@prisma+client@2.24.1_prisma@2.24.1/node_modules/@prisma/client: Running postinstall script, done in 2.9s
node_modules/.pnpm/blitz@0.37.0_cbbb76279fdd80bd27f5a68684189b06/node_modules/blitz: Running postinstall script, done in 308ms

dependencies:
+ @prisma/client 2.24.1
+ @types/preview-email 2.0.0
+ @types/react 17.0.10
+ blitz 0.37.0
+ eslint 7.28.0
+ final-form 4.20.2
+ husky 6.0.0
+ lint-staged 10.5.4 (11.0.0 is available)
+ prettier 2.3.1
+ prettier-plugin-prisma 0.11.1
+ pretty-quick 3.1.0
+ preview-email 3.0.4
+ prisma 2.24.1
+ react 0.0.0-experimental-0eea57724 (17.0.2 is available)
+ react-dom 0.0.0-experimental-0eea57724 (17.0.2 is available)
+ react-error-boundary 3.1.3
+ react-final-form 6.5.3
+ typescript 4.2.4 (4.3.2 is available)
+ zod 3.1.0

> blitz-pnpm@1.0.0 prepare /home/chronark/github/chronark/blitzWithPnpm/blitz-pnpm
> husky install

husky - Git hooks installed

> blitz-pnpm@1.0.0 build /home/chronark/github/chronark/blitzWithPnpm/blitz-pnpm
> blitz build

✔ Compiled
info  - Loaded env from /home/chronark/github/chronark/blitzWithPnpm/blitz-pnpm/.env
info  - Using webpack 5. Reason: no custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types...
info  - Creating an optimized production build...
info  - Using external babel configuration from /home/chronark/github/chronark/blitzWithPnpm/blitz-pnpm/babel.config.js
info  - Compiled successfully
info  - Collecting page data...
info  - Generating static pages (0/7)

Error occurred prerendering page "/reset-password". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read property 'useRef' of null
    at Object.exports.useRef (/home/chronark/github/chronark/blitzWithPnpm/blitz-pnpm/node_modules/.pnpm/react@0.0.0-experimental-0eea57724/node_modules/react/cjs/react.production.min.js:25:408)
    at useConstant (/home/chronark/github/chronark/blitzWithPnpm/blitz-pnpm/node_modules/.pnpm/react-final-form@6.5.3_a4d3084a967171ae6c313df9fc89e061/node_modules/react-final-form/dist/react-final-form.cjs.js:96:39)
    at ReactFinalForm (/home/chronark/github/chronark/blitzWithPnpm/blitz-pnpm/node_modules/.pnpm/react-final-form@6.5.3_a4d3084a967171ae6c313df9fc89e061/node_modules/react-final-form/dist/react-final-form.cjs.js:203:14)
    at d (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:34:498)
    at Za (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:37:16)
    at a.b.render (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:43:48)
    at a.b.read (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:83)
    at exports.renderToString (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:138)
    at Object.renderPage (/home/chronark/github/chronark/blitzWithPnpm/node_modules/next/dist/next-server/server/render.js:54:854)
    at Function.getInitialProps (/home/chronark/github/chronark/blitzWithPnpm/node_modules/next/dist/pages/_document.js:9:159)
info  - Generating static pages (1/7)

Error occurred prerendering page "/signup". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read property 'useRef' of null
    at Object.exports.useRef (/home/chronark/github/chronark/blitzWithPnpm/blitz-pnpm/node_modules/.pnpm/react@0.0.0-experimental-0eea57724/node_modules/react/cjs/react.production.min.js:25:408)
    at useConstant (/home/chronark/github/chronark/blitzWithPnpm/blitz-pnpm/node_modules/.pnpm/react-final-form@6.5.3_a4d3084a967171ae6c313df9fc89e061/node_modules/react-final-form/dist/react-final-form.cjs.js:96:39)
    at ReactFinalForm (/home/chronark/github/chronark/blitzWithPnpm/blitz-pnpm/node_modules/.pnpm/react-final-form@6.5.3_a4d3084a967171ae6c313df9fc89e061/node_modules/react-final-form/dist/react-final-form.cjs.js:203:14)
    at d (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:34:498)
    at Za (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:37:16)
    at a.b.render (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:43:48)
    at a.b.read (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:83)
    at exports.renderToString (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:138)
    at Object.renderPage (/home/chronark/github/chronark/blitzWithPnpm/node_modules/next/dist/next-server/server/render.js:54:854)
    at Function.getInitialProps (/home/chronark/github/chronark/blitzWithPnpm/node_modules/next/dist/pages/_document.js:9:159)
info  - Generating static pages (3/7)

Error occurred prerendering page "/login". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read property 'useRef' of null
    at Object.exports.useRef (/home/chronark/github/chronark/blitzWithPnpm/blitz-pnpm/node_modules/.pnpm/react@0.0.0-experimental-0eea57724/node_modules/react/cjs/react.production.min.js:25:408)
    at useConstant (/home/chronark/github/chronark/blitzWithPnpm/blitz-pnpm/node_modules/.pnpm/react-final-form@6.5.3_a4d3084a967171ae6c313df9fc89e061/node_modules/react-final-form/dist/react-final-form.cjs.js:96:39)
    at ReactFinalForm (/home/chronark/github/chronark/blitzWithPnpm/blitz-pnpm/node_modules/.pnpm/react-final-form@6.5.3_a4d3084a967171ae6c313df9fc89e061/node_modules/react-final-form/dist/react-final-form.cjs.js:203:14)
    at d (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:34:498)
    at Za (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:37:16)
    at a.b.render (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:43:48)
    at a.b.read (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:83)
    at exports.renderToString (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:138)
    at Object.renderPage (/home/chronark/github/chronark/blitzWithPnpm/node_modules/next/dist/next-server/server/render.js:54:854)
    at Function.getInitialProps (/home/chronark/github/chronark/blitzWithPnpm/node_modules/next/dist/pages/_document.js:9:159)
info  - Generating static pages (5/7)

Error occurred prerendering page "/forgot-password". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read property 'useRef' of null
    at Object.exports.useRef (/home/chronark/github/chronark/blitzWithPnpm/blitz-pnpm/node_modules/.pnpm/react@0.0.0-experimental-0eea57724/node_modules/react/cjs/react.production.min.js:25:408)
    at useConstant (/home/chronark/github/chronark/blitzWithPnpm/blitz-pnpm/node_modules/.pnpm/react-final-form@6.5.3_a4d3084a967171ae6c313df9fc89e061/node_modules/react-final-form/dist/react-final-form.cjs.js:96:39)
    at ReactFinalForm (/home/chronark/github/chronark/blitzWithPnpm/blitz-pnpm/node_modules/.pnpm/react-final-form@6.5.3_a4d3084a967171ae6c313df9fc89e061/node_modules/react-final-form/dist/react-final-form.cjs.js:203:14)
    at d (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:34:498)
    at Za (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:37:16)
    at a.b.render (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:43:48)
    at a.b.read (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:83)
    at exports.renderToString (/home/chronark/github/chronark/blitzWithPnpm/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:138)
    at Object.renderPage (/home/chronark/github/chronark/blitzWithPnpm/node_modules/next/dist/next-server/server/render.js:54:854)
    at Function.getInitialProps (/home/chronark/github/chronark/blitzWithPnpm/node_modules/next/dist/pages/_document.js:9:159)
info  - Generating static pages (7/7)

> Build error occurred
Error: Export encountered errors on following paths:
        /forgot-password
        /login
        /reset-password
        /signup
    at /home/chronark/github/chronark/blitzWithPnpm/node_modules/next/dist/export/index.js:34:1106
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Span.traceAsyncFn (/home/chronark/github/chronark/blitzWithPnpm/node_modules/next/dist/telemetry/trace/trace.js:6:584)
    at async /home/chronark/github/chronark/blitzWithPnpm/node_modules/next/dist/build/index.js:46:49
    at async Span.traceAsyncFn (/home/chronark/github/chronark/blitzWithPnpm/node_modules/next/dist/telemetry/trace/trace.js:6:584)
    at async /home/chronark/github/chronark/blitzWithPnpm/node_modules/next/dist/build/index.js:28:1475
    at async Span.traceAsyncFn (/home/chronark/github/chronark/blitzWithPnpm/node_modules/next/dist/telemetry/trace/trace.js:6:584)
 ERROR  Command failed with exit code 1.
```

### Paste all relevant code snippets here:

-

### What are detailed steps to reproduce this?

```bash
npx blitz new blitz-pnpm
cd blitz-pnpm
rm -rf node_modules yarn.lock
pnpm install

pnpm run build // or dev
```

### Run `blitz -v` and paste the output here:

```
npx blitz -v                                   
Linux 5.11 | linux-x64 | Node: v14.17.0

blitz: 0.37.0 (local)

  Package manager: yarn 
  System:
    OS: Linux 5.11 Pop!_OS 20.10
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 22.94 GB / 31.37 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.17.0 - ~/n/bin/node
    Yarn: 1.22.10 - ~/n/bin/yarn
    npm: 6.14.13 - ~/n/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.24.1 => 2.24.1 
    blitz: 0.37.0 => 0.37.0 
    prisma: 2.24.1 => 2.24.1 
    react: 0.0.0-experimental-0eea57724 => 0.0.0-experimental-0eea57724 
    react-dom: 0.0.0-experimental-0eea57724 => 0.0.0-experimental-0eea57724 
    typescript: ~4.2 => 4.2.4 

```

**Comment by flybayer** [comment] 2021-06-09 15:55
Thanks @chronark. I think this is a duplicate of https://github.com/blitz-js/blitz/issues/2436. Can you confirm?

**Comment by chronark** [comment] 2021-06-10 14:59
Yeah that seems to be the same issue. Feel free to close this one ;)

**Closed** 2021-06-10 16:25 UTC
Labels: kind/bug, status/triage
