### ISSUE TITLE
dnd list in Base Web recipe error

### ISSUE THREAD

**Issue by ivanthemeh** [blitz-js/blitz#1472] opened 2020-11-16 22:15 UTC
I have installed a vanilla blitzjs app and used the base web recipe. I was testing some components and I noticed an issue with the dnd list. When I move the items I get an error.

```
Unhandled Runtime Error

TypeError: _this.ghostRef.current is null
Call Stack
List/_this.moveOtherItems
../../../node_modules/react-movable/lib/List.js (196:0)
List/_this.onMove
../../../node_modules/react-movable/lib/List.js (193:0)
List/_this.onMouseMove
../../../node_modules/react-movable/lib/List.js (176:0)
wrapperFn/frameId<
../../../node_modules/react-movable/lib/utils.js (84:0)
```

1.

### Versions

```
debug: blitzPkgPath: /Users/ivan/.nvm/versions/node/v12.14.1/lib/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/ivan/.nvm/versions/node/v12.14.1/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js

macOS Mojave | darwin-x64 | Node: v12.14.1

blitz: 0.25.0 (global)

  Package manager: npm
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 331.30 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: Not Found
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: Not Found
    @prisma/client: Not Found
    blitz: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

### Other

Please include applicable logs and screenshots that show your problem.

**Comment by flybayer** [comment] 2020-11-17 01:54
@ivanthemeh possibly this is an issue with Base Web and React concurrent mode. I suggest opening an issue on their github.

**Comment by ivanthemeh** [comment] 2020-11-17 10:28
Yea I made one in their github first and they sent me here.

**Comment by konradkalemba** [comment] 2020-11-17 17:49
@ivanthemeh I tried to reproduce your bug on a new blitz app but everything is working as expected. Can you provide more information on how to reproduce this error?

**Comment by ivanthemeh** [comment] 2020-11-17 23:17
literally all I did was install a fresh blitz app and used the base-web recipe... I was able to track down the line of code and hack it so the errors stopped.

**Comment by flybayer** [comment] 2020-11-18 02:07
Yeah @konradkalemba is right, looks like a react-movable bug

**Comment by flybayer** [comment] 2020-11-18 02:07
ok to close this?

**Comment by MrLeebo** [comment] 2020-12-04 22:05
👌

**Closed by MrLeebo** 2020-12-04 22:05 UTC
Labels: status/triage
