### ISSUE TITLE
Prisma query engine hash mismatch

### ISSUE THREAD

**Issue by netheril96** [blitz-js/blitz#1005] opened 2020-09-04 02:32 UTC
### What is the problem?
When running `blitz new`, it shows error

```UnhandledPromiseRejectionWarning: Error: sha256 of https://binaries.prisma.sh/all_commits/650b5d0348ec38ae61e1e7db69bb54808418ede4/debian-openssl-1.1.x/query-engine.gz (zipped) should be 3be50ce57ddc551595e45cb0aa3204f26567c3ae7fc729b05073265dbb60aa6a but is 4a54930dac67a16e42a037cf1ff9b238a8acecbc557b5924c7af5e23389be4ec```

I tried downloading the file in different networks and in my cloud VM, and their sha256 is always `4a54930dac67a16e42a037cf1ff9b238a8acecbc557b5924c7af5e23389be4ec`, so it seems that the expected checksum written in `blitz` is wrong.

### Steps to Reproduce

1. `blitz new anything`

### Versions

```
output of `blitz --version --verbose`

You are using alpha software - if you have any problems, please open an issue here:
    https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /home/rsy/Documents/btest/node_modules/blitz/dist/index.js
debug: cliPkgPath: /home/rsy/Documents/btest/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js 

Linux 5.4 | linux-x64 | Node: v12.18.3

blitz: 0.21.1 (global)
blitz: 0.21.1 (local)

  Package manager: npm 
  System:
    OS: Linux 5.4 Linux Mint 20 (Ulyana)
    CPU: (4) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 723.51 MB / 4.70 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: Not Found
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.6.1 => 2.6.1 
    @prisma/client: 2.6.1 => 2.6.1 
    blitz: 0.21.1 => 0.21.1 
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    typescript: 3.9.7 => 3.9.7 

```

### Other

Please include applicable logs and screenshots that show your problem.

**Comment by LoriKarikari** [comment] 2020-09-04 10:08
Thanks for reporting this issue @netheril96.

**Comment by flybayer** [comment] 2020-09-08 00:52
Hey @netheril96! We rely on npm/yarn for this, so there's no checksum checking inside Blitz itself. Can you try this again now and see if it's resolved? It could have been some type of temporary upstream issue.

**Comment by ntgussoni** [comment] 2020-09-18 15:29
This seems to be an issue with npm and @prisma/cli install. 
I could reproduce it with npm, installing it with yarn made it work `yarn add @prisma/cli --dev`

**Comment by flybayer** [comment] 2020-09-18 22:09
Ok thanks @ntgussoni. Will go ahead and close this.

**Closed by flybayer** 2020-09-18 22:09 UTC
Labels: kind/bug, status/triage
