### ISSUE TITLE
[Windows] Blitz crashes after following initial build instructions  

### ISSUE THREAD

**Issue by rhoffer21** [blitz-js/blitz#299] opened 2020-04-27 16:30 UTC
### What is the problem?
Installed blitz, setup a test project and am receiving the following error:
Module not found: Can't resolve 'child_process' in node_modules\@prisma\client\runtime' Could not find files for /projects in .next/build-manifest.json

### Steps to Reproduce: 
1.Created a new blitz application
2. Ran blitz start
3. Copied the schema from the documentation into schema.db
4. ran blitz db migrate and blitz generate all project
5. navigate to localhost:3000/projects and the app crashes with error:

Module not found: Can't resolve 'child_process' in node_modules\@prisma\client\runtime' Could not find files for /projects in .next/build-manifest.json

### Versions:
Windows 10 | win32-x64 | Node: v10.15.3

blitz: 0.7.0 (global)

**Comment by rhoffer21** [comment] 2020-04-27 18:32
I just noticed this says it requires node v12 and im rocking v10.  Let me upgrade real fast and see if that does the trick.

**Comment by wKovacs64** [comment] 2020-04-28 02:39
Confirmed it's crashing on Windows 10, although I'm getting a different error:

```
C:\dev\test\my-blitz\node_modules\snapdragon\lib\parser.js:474
        throw new Error('no parsers registered for: "' + self.input.slice(0, 5) + '"');
        ^

Error: no parsers registered for: "]"
    at parse (C:\dev\test\my-blitz\node_modules\snapdragon\lib\parser.js:473:15)
    at Parser.parse (C:\dev\test\my-blitz\node_modules\snapdragon\lib\parser.js:477:24)
    at Snapdragon.parse (C:\dev\test\my-blitz\node_modules\snapdragon\index.js:122:28)
    at Snapdragon.<anonymous> (C:\dev\test\my-blitz\node_modules\braces\lib\braces.js:40:45)
    at Braces.parse (C:\dev\test\my-blitz\node_modules\braces\lib\braces.js:66:26)
    at Braces.expand (C:\dev\test\my-blitz\node_modules\braces\lib\braces.js:87:18)
    at create (C:\dev\test\my-blitz\node_modules\braces\index.js:142:15)
    at memoize (C:\dev\test\my-blitz\node_modules\braces\index.js:298:13)
    at Function.braces.create (C:\dev\test\my-blitz\node_modules\braces\index.js:165:10)
    at Function.braces.expand (C:\dev\test\my-blitz\node_modules\braces\index.js:81:17)
```

Something is bombing on the `app\projects\pages\projects\[id]` directory (or the `app\projects\pages\projects\[id].tsx` file, maybe - probably both). I added some logging to the snapdragon parser and this was what I got just before the error:

```
parse -> input: C:\dev\test\my-blitz\app\projects\pages\projects\[id]
parse -> input: \dev\test\my-blitz\app\projects\pages\projects\[id]
parse -> input: \test\my-blitz\app\projects\pages\projects\[id]
parse -> input: \my-blitz\app\projects\pages\projects\[id]
parse -> input: \app\projects\pages\projects\[id]
parse -> input: \projects\pages\projects\[id]
parse -> input: \pages\projects\[id]
parse -> input: \projects\[id]
parse -> input: \[id]
parse -> input: ]
```

**Comment by Skn0tt** [comment] 2020-04-28 13:52
Duplicate of #269

**Comment by Skn0tt** [comment] 2020-04-28 13:54
It's interesting that there's a `/` missing in `node_modules@prisma\client\runtime`, looks like a typo in some template.

**Comment by Skn0tt** [comment] 2020-04-28 13:54
Sorry for premature closing, got confused.

**Comment by wKovacs64** [comment] 2020-04-28 20:26
> It's interesting that there's a `/` missing in `node_modules@prisma\client\runtime`, looks like a typo in some template.

I think that was just in his issue text, my error locally has the slash there (FWIW).

**Comment by flybayer** [comment] 2020-05-04 13:40
@rhoffer21 can you verify that you aren't using `db` directly inside a react component? 

If you aren't, can you put up a repo with your project so we can reproduce?

Related: #385

**Comment by flybayer** [comment] 2020-05-04 15:46
If you are still having the `child_process` bug and aren't importing the db into a component, then please install the new blitz version `0.8.2` and see if that fixes it!

**Comment by wKovacs64** [comment] 2020-05-05 00:47
This error is still an issue for Windows users as of v0.8.2 (reported in Slack and confirmed first-hand). The included store example throws this error and it's not making any `db` calls in components. It _is_ importing from `db`, but only the generated types. Going through the tutorial still fails at the point where you are instructed to visit `/projects` after generating your `Project` model scaffolding.

(I tried a `--js` project to see what it would do without importing from 'db' at all, but that fails in a different, unrelated way.)

**Comment by flybayer** [comment] 2020-05-05 08:25
Ok weird..

**Closed** 2020-05-07 07:40 UTC
Labels: kind/bad-experience, kind/bug, needs investigation, os/windows, status/ready-to-work-on
