### ISSUE TITLE
Vercel: Cannot find module '/var/task/.next/blitz/db.js'

### ISSUE THREAD

**Issue by rodrigoehlers** [blitz-js/blitz#2075] opened 2021-03-06 12:07 UTC
### What is the problem?

After deploying my app to Vercel, I'm unable to access an authenticated server side rendered page. In the functions tab I'm able to see the following error:

```
[GET] /c/pre - 21:17:25:64
ver.cjs.prod.js:1008:41)
    at getSession (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:704:29)
    at /var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:668:13
    at dispatch (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:190:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js',
    '/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.js',
    '/var/task/.next/serverless/pages/c/pre.js',
    '/var/task/now__launcher.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
2021-03-05T20:17:27.036Z	4a13edcc-0d11-48bd-ad39-033c53ec990c	ERROR	Unhandled Promise Rejection 	{"stack":"Runtime.UnhandledPromiseRejection: Error: Cannot find module '/var/task/.next/blitz/db.js'\nRequire stack:\n- /var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js\n- /var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.js\n- /var/task/.next/serverless/pages/c/pre.js\n- /var/task/now__launcher.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js\n    at process.<anonymous> (/var/runtime/index.js:35:15)\n    at process.emit (events.js:326:22)\n    at processPromiseRejections (internal/process/promises.js:209:33)\n    at processTicksAndRejections (internal/process/task_queues.js:98:32)","message":"Error: Cannot find module '/var/task/.next/blitz/db.js'\nRequire stack:\n- /var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js\n- /var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.js\n- /var/task/.next/serverless/pages/c/pre.js\n- /var/task/now__launcher.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","reason":{"stack":"Error: Cannot find module '/var/task/.next/blitz/db.js'\nRequire stack:\n- /var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js\n- /var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.js\n- /var/task/.next/serverless/pages/c/pre.js\n- /var/task/now__launcher.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:667:27)\n    at Module.require (internal/modules/cjs/loader.js:887:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at getDb (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:540:25)\n    at Object.getSession (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:550:12)\n    at getSessionKernel (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:1008:41)\n    at getSession (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:704:29)\n    at /var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:668:13\n    at dispatch (/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:190:32)","message":"Cannot find module '/var/task/.next/blitz/db.js'\nRequire stack:\n- /var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js\n- /var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.js\n- /var/task/.next/serverless/pages/c/pre.js\n- /var/task/now__launcher.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","code":"MODULE_NOT_FOUND","requireStack":["/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js","/var/task/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.js","/var/task/.next/serverless/pages/c/pre.js","/var/task/now__launcher.js","/var/runtime/UserFunction.js","/var/runtime/index.js"]},"promise":{}}
Unknown application error occurred
```

### What are detailed steps to reproduce this?

As this doesn't happen on local, I'm unable to specify the steps to reproduce this.

### Run `blitz -v` and paste the output here:

```
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

macOS Big Sur | darwin-x64 | Node: v14.16.0

blitz: 0.31.0 (global)
blitz: 0.31.1 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.2.2
    CPU: (8) x64 Apple M1
    Memory: 42.70 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 7.6.1 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.17 => 2.17.0 
    blitz: 0.31.1 => 0.31.1 
    prisma: ~2.17 => 2.17.0 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: ~4.1 => 4.1.5 


```

Please note that I discovered this bug after pushing changes to Vercel with my Intel-based Mac. The M1 just happens to be the one I'm creating this issue on. The error doesn't occur on local at all, no matter if it's Intel or Apple Silicon.

**Comment by flybayer** [comment] 2021-03-06 16:05
@rodrigoehlers this is on a SSR page? Please post the contents of your `getServerSideProps` function

**Comment by rodrigoehlers** [comment] 2021-03-06 18:48
Yes, sorry I wrote

> ... server side rendered app.

I've updated the description. Yes, it is a server side rendered __page__.

The content of `getServerSideProps` is the following:
```js
export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  const entity = await invokeWithMiddleware(getEntity, null, ctx);
  return {
    props: {
      entity,
    },
  };
};
```

This is `getEntity`:
```js
import { Ctx, resolver, NotFoundError } from 'blitz';
import db from 'db';
import { PublicEntityResult } from 'app/_entity/validations';

const getEntity = resolver.pipe(
  resolver.authorize(['X', 'Y', 'Z']),
  async (_, ctx: Ctx): Promise<PublicEntityResult> => {
    const userId = ctx.session.userId;

    const entity = await db.entity.findFirst({
      where: {
        user: {
          id: userId!,
        },
      },
    });

    if (! entity) {
      throw new NotFoundError(`Not found for user '${userId}'.`);
    }

    return entity;
  }
);

export default getEntity;
```

**Comment by flybayer** [comment] 2021-03-08 23:09
@rodrigoehlers ok looks like this is a duplicate of https://github.com/blitz-js/blitz/issues/794

Can you look at that and try the workaround listed there?

**Comment by rodrigoehlers** [comment] 2021-03-09 15:42
@flybayer I did another deployment, adding `path.resolve('.next/blitz/db.js')` as that path seems to be mentioned in the error message I posted. It does indeed work now. Not sure if this has any other implications though, should I add a comment to the original thread #794?

**Comment by flybayer** [comment] 2021-03-09 21:57
Ah yes, sorry about that. I just updated that issue with the correct path (it changed since it was opened)

**Closed by flybayer** 2021-03-09 21:57 UTC
Labels: kind/bug, status/triage
