### ISSUE TITLE
Start app in production w/o rebuilding

### ISSUE THREAD

**Issue by dajinchu** [blitz-js/blitz#543] opened 2020-05-21 20:28 UTC
### What do you want and why?

Most other frameworks (gatsby, next, create-react-app) make you run `build` before `start`. `start` just runs or serves the built files. For blitz, `start` is actually for development, and `start --production` always rebuilds. It would be great for startup time to have some way to start a built blitz app other than installing `next` into production.

### Possible implementation(s)

Make `start --production` not rebuild and simply look for built files.

**Comment by Zeko369** [comment] 2020-05-21 22:07
Duplicate of #540, let's keep it there (checksum suggestion)

**Closed by Zeko369** 2020-05-21 22:07 UTC
Labels: status/triage
