### ISSUE TITLE
cookiePrefix not working in production builds

### ISSUE THREAD

**Issue by LikeCarter** [blitz-js/blitz#2428] opened 2021-06-01 00:56 UTC
### What is the problem?

Wow. This was a full 5 days of debugging.

You cannot authenticate in production builds of blitzjs. The client side cannot find the correct public data cookie.

It seems that the cookiePrefix setting in `blitz.config.ts` is not actually implemented properly in production builds (for some reason?).

Leading to all kinds of mysterious auth errors.

### Paste all your error logs here:

```
e: You must be logged in to access this
```

### Paste all relevant code snippets here:

It seems "blitz_***" is always passed as name.

```
function readCookie(name) {
  if (typeof document === "undefined") return null;
  var cookie = document.cookie;
  var setPos = cookie.search(new RegExp("\\b" + name + "="));
  var stopPos = cookie.indexOf(";", setPos);
  var res;
  if (!~setPos) return null;
  res = decodeURIComponent(cookie.substring(setPos, ~stopPos ? stopPos : undefined).split("=")[1]);
  return res.charAt(0) === "{" ? JSON.parse(res) : res;
}
```

### What are detailed steps to reproduce this?

1. Set cookiePrefix to something other than blitz - in my case I set it to `eva`
2. yarn build
3. yarn start

### Run `blitz -v` and paste the output here:

```
blitz: 0.36.3 (global)
blitz: 0.36.3 (local)
```

**Comment by flybayer** [comment] 2021-06-01 19:57
Hey @LikeCarter, sorry, that sounds super painful 😬 

I just tested and cannot reproduce locally with `blitz build && blitz start`.

Are you reproducing locally? Or is this only happening on a cloud provider? If so, which?

**Comment by ormarek** [comment] 2021-06-03 11:38
@LikeCarter can you post your actual config here? I've also tried it and wasn't able to reproduce issue

**Comment by brapifra** [comment] 2021-06-06 19:23
I'm also suffering this :cry: 
Not working on

**Comment by mabadir** [comment] 2021-06-06 19:50
Hi @brapifra, would you share your config file?

**Comment by brapifra** [comment] 2021-06-06 20:02
@mabadir 
```
const { sessionMiddleware, simpleRolesIsAuthorized } = require("blitz")

module.exports = {
  env: {
    PUBLIC_URL: process.env.PUBLIC_URL,
  },
  middleware: [
    sessionMiddleware({
      cookiePrefix: "hello",
      isAuthorized: simpleRolesIsAuthorized,
    }),
  ],
  async rewrites() {
    return {
      afterFiles: [
        {
          source: "/live/:slug*",
          destination: "/api/live/:slug*",
        },
      ],
      fallback: [
        {
          source: "/api/:path*",
          destination: "http://anotherweb.com/2d/:path*",
        },
      ],
    }
  },
  /* Uncomment this to customize the webpack config
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    // Note: we provide webpack above so you should not `require` it
    // Perform customizations to webpack config
    // Important: return the modified config
    return config
  },
  */
}
```

**Comment by flybayer** [comment] 2021-06-07 20:05
I just tested this on Vercel with a brand new app blitz `0.36.4` and it's working correctly 🤔 

Are you able to share any more details? How big is your app? With how Vercel does things, it could be something that breaks once your app gets to a certain size?? idk.

**Comment by LikeCarter** [comment] 2021-06-08 23:38
Sorry for the late response - I'm swamped. 


This was the config file. *Switching from "arctic" to "blitz" solved my issue without change anything else.*
```javascript
import { sessionMiddleware, simpleRolesIsAuthorized } from "blitz"
const MomentLocalesPlugin = require("moment-locales-webpack-plugin")
const withAntdLess = require("next-plugin-antd-less")
const withBundleAnalyzer = require("@next/bundle-analyzer")({
  enabled: process.env.ANALYZE === "true",
})

module.exports = (phase, { defaultConfig }) =>
  withBundleAnalyzer(
    withAntdLess({
      middleware: [
        sessionMiddleware({
          cookiePrefix: "arctic",
          isAuthorized: simpleRolesIsAuthorized,
        }),
      ],
      webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
        config.plugins.push(new MomentLocalesPlugin())
        return config
      },
    })
  )
```

This is my package.json for versions
```javascript
{
  "name": "evatir",
  "version": "1.0.1",
  "license": "AGPL-3.0-or-later",
  "engines": {
    "node": "^15.7.0",
    "npm": "^7.14.0",
    "yarn": "^1.22.5"
  },
  "prisma": {
    "schema": "db/schema.prisma"
  },
  "prettier": {
    "semi": false,
    "printWidth": 100
  },
  "lint-staged": {
    "*.{js,ts,tsx}": [
      "eslint --fix"
    ]
  },
  "dependencies": {
    "@next/bundle-analyzer": "^10.2.3",
    "@prisma/client": "~2.20",
    "@stripe/stripe-js": "1.13.2",
    "antd": "^4.16.0",
    "aws-sdk": "2.915.0",
    "axios": "0.21.1",
    "blitz": "0.36.3",
    "envsafe": "2.0.3",
    "final-form": "4.20.2",
    "js-base64": "^3.6.1",
    "lodash": "4.17.21",
    "match-sorter": "6.3.0",
    "micro": "9.3.4",
    "micro-cors": "0.1.1",
    "mobx": "6.2.0",
    "mobx-react-lite": "3.2.0",
    "moment": "2.29.1",
    "moment-locales-webpack-plugin": "^1.2.0",
    "next-plugin-antd-less": "^1.2.1",
    "passport-azure-ad": "^4.3.0",
    "passport-google-oauth20": "2.0.0",
    "patch-package": "6.4.7",
    "prisma": "~2.20",
    "react": "0.0.0-experimental-6a589ad71",
    "react-dom": "0.0.0-experimental-6a589ad71",
    "react-error-boundary": "3.1.3",
    "react-final-form": "6.5.3",
    "stripe": "8.144.0",
    "swr": "0.5.5",
    "typescript": "~4.2",
    "uuid": "8.3.2",
    "zod": "3.1.0"
  },
  "devDependencies": {
    "@types/micro": "7.3.4",
    "@types/micro-cors": "0.1.1",
    "@types/passport-google-oauth20": "2.0.7",
    "@types/preview-email": "2.0.0",
    "@types/react": "17.0.8",
    "babel-plugin-import": "1.13.3",
    "eslint": "^7.23.0",
    "lint-staged": "^10.5.4",
    "prettier": "^2.2.1",
    "prettier-plugin-prisma": "0.7.0",
    "pretty-quick": "3.1.0",
    "preview-email": "3.0.4"
  },
  "private": true
}
```

**Comment by flybayer** [comment] 2021-06-09 15:52
Thanks @LikeCarter. Also important question: does this happen locally or in the cloud or both? (And if in the cloud, which cloud?)

**Comment by brapifra** [comment] 2021-06-10 18:02
It's finally working for me on Vercel with v0.37.0

**Comment by flybayer** [comment] 2021-06-14 15:56
Ok going to close this for now then. If any of you still have an issue we can reopen

**Closed by flybayer** 2021-06-14 15:56 UTC
Labels: kind/bug, status/ready-to-work-on
