### ISSUE TITLE
`blitz dev` get's stuck on _manifest.json

### ISSUE THREAD

**Issue by andreasasprou** [blitz-js/blitz#632] opened 2020-06-06 08:03 UTC
### What is the problem?

Unable to run `blitz dev` after upgrading to v0.12

### Steps to Reproduce

1. Install blitz@0.12
2. Run `blitz dev`

### Versions

```
debug: local
debug: pkgPath: /Users/--proj--/node_modules/@blitzjs/cli 

macOS Catalina | darwin-x64 | Node: v12.13.0

blitz: 0.8.0 (global)
blitz: 0.12.0 (local)
```

### Other

I've tried removing `.next` and `.blitz`

```
➜  yarn dev           
yarn run v1.21.1
$ blitz start
You are using alpha software - if you have any problems, please open an issue here:
  https://github.com/blitz-js/blitz/issues/new/choose

✔ Prepped for launch
ready - started server on http://localhost:3000
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

Error: > Couldn't find a `pages` directory. Please create one under the project root
    at findPagesDir (/Users/--proj--/node_modules/next/dist/lib/find-pages-dir.js:3:170)
    at new DevServer (/Users/--proj--/node_modules/next/dist/server/next-dev-server.js:1:4325)
    at createServer (/Users/--proj--/node_modules/next/dist/server/next.js:2:300)
    at start (/Users/--proj--t/node_modules/next/dist/server/lib/start-server.js:1:323)
    at nextDev (/Users/--proj--/node_modules/next/dist/cli/next-dev.js:21:279)
    at /Users/--proj--/node_modules/next/dist/bin/next:28:341
'next dev' failed with status code: 1
```

**Comment by flybayer** [comment] 2020-06-06 08:05
@andreasasprou can you try with `0.13.0-canary.3`?

**Comment by andreasasprou** [comment] 2020-06-06 08:06
It stalls at `_manifest.json` with `0.13.0-canary.3`:

```
yarn run v1.21.1
$ blitz start
You are using alpha software - if you have any problems, please open an issue here:
  https://github.com/blitz-js/blitz/issues/new/choose

◣ _manifest.json
```

**Comment by ryardley** [comment] 2020-06-06 08:12
Hmm... interesting there should be a fix for this in 0.13.0-canary.3

**Comment by ryardley** [comment] 2020-06-06 08:12
Can you push a repo with this problem?

**Comment by andreasasprou** [comment] 2020-06-06 08:20
I can't seem to re-create it in a new repo & can't push mine. Is it possible to make the logging a little more verbose so I/we can debug it?

**Comment by ryardley** [comment] 2020-06-06 08:22
This will likely happen before 0.13.0-canary.3 can you guarantee you are not using an older version?

**Comment by andreasasprou** [comment] 2020-06-06 08:24
```
success Saved 8 new dependencies.
info Direct dependencies
└─ blitz@0.13.0-canary.3
info All dependencies
├─ @blitzjs/cli@0.13.0-canary.3
├─ @blitzjs/core@0.13.0-canary.3
├─ @blitzjs/file-pipeline@0.13.0-canary.3
├─ @blitzjs/generator@0.13.0-canary.3
├─ @blitzjs/repl@0.13.0-canary.3
├─ @blitzjs/server@0.13.0-canary.3
├─ blitz@0.13.0-canary.3
└─ folder-hash@3.3.1
```

All of the above match when I check in the relevant `package.json`'s in `node_modules`

**Comment by andreasasprou** [comment] 2020-06-06 08:25
Ah, wait a second. Look at the version I posed in the initial issue... Mis-match in cli version

**Comment by ryardley** [comment] 2020-06-06 08:26
Try using `yarn blitz start` does that help at all?

**Comment by andreasasprou** [comment] 2020-06-06 08:26
Turns out, I ran the above after switching back to 0.12. I am indeed running `blitz: 0.13.0-canary.3 (local)`  with `yarn blitz start` stalling at `_manifest.json`

**Comment by ryardley** [comment] 2020-06-06 08:31
so sorry for what is the output of `yarn blitz --version --verbose`

**Comment by andreasasprou** [comment] 2020-06-06 08:32
```
You are using alpha software - if you have any problems, please open an issue here:
  https://github.com/blitz-js/blitz/issues/new/choose

debug: local
debug: pkgPath: /Users/--proj--/node_modules/@blitzjs/cli 

macOS Catalina | darwin-x64 | Node: v12.13.0

blitz: 0.13.0-canary.3 (global)
blitz: 0.13.0-canary.3 (local)

```

**Comment by ryardley** [comment] 2020-06-06 09:01
Ok I will add an issue to increase logger verbocity but in the meantime I need a way to reproduce this somehow by posting a repo somewhere. You can get some extra logging currently using DEBUG=1 env var but I am not sure there is enough logging happening to provide much insight. Are any files missing from `.blitz/caches/dev`?

**Comment by andreasasprou** [comment] 2020-06-06 10:48
Everything seems to be in caches/dev (inc `_manifest.json`). `DEBUG=1` provides no other information.

**Comment by ryardley** [comment] 2020-06-07 01:08
@andreasasprou I have reached out over blitz slack to try and work out how to reproduce this.

**Comment by ryardley** [comment] 2020-06-08 08:16
If anyone comes across this issue and can share a repository with me to replicate this I would really appreciate it.

**Comment by gielcobben** [comment] 2020-06-14 15:32
Today I wanted to update to `v0.14.0` since `v0.13.0` was not working for me due to this bug. Unfortunately `v0.14.0` also doesn't work. It keeps stuck at `_manifest.json`.

I checked what was inside `_manifest.json` and compared it to the `_manifest.json` from the `v0.12.0` version which builds and start blitz without any problem. The keys and values inside the `_manifest.json` file of the latest versions (`v0.13.0`/`v0.14.0`) contained a lot of `.git` paths. 

Could this information help with figuring out a possible fix?

**Comment by ryardley** [comment] 2020-06-15 00:37
Thank you @gielcobben. So I guess that means the dangling promise was not the fix. I had a look and I thought I had debounced writing to the manifest but it must have been on a branch that didn't get in. If the problem is a highwatermark one this won't solve the underlying problem but it might keep the threshold low enough to avoid the issue and speed up the build which could make a difference. I will throw up a PR today.

**Comment by ryardley** [comment] 2020-06-15 01:48
> Today I wanted to update to `v0.14.0` since `v0.13.0` was not working for me due to this bug. Unfortunately `v0.14.0` also doesn't work. It keeps stuck at `_manifest.json`.
> 
> 
> 
> I checked what was inside `_manifest.json` and compared it to the `_manifest.json` from the `v0.12.0` version which builds and start blitz without any problem. The keys and values inside the `_manifest.json` file of the latest versions (`v0.13.0`/`v0.14.0`) contained a lot of `.git` paths. 
> 
> 
> 
> Could this information help with figuring out a possible fix?

It should certainly not include any .git paths!

**Comment by flybayer** [comment] 2020-06-15 02:43
I just published `0.14.1`. Can someone test that and see if you still have the stuck at _manifest issue?

**Comment by ryardley** [comment] 2020-06-15 05:09
Can confirm .git paths are not being ignored despite being set in the ignoredFolder list. Will investigate.

**Comment by andreasasprou** [comment] 2020-06-15 05:12
https://www.loom.com/share/8c20160d04e448f1b1fef3806a87e3d6

**Comment by ryardley** [comment] 2020-06-15 05:20
This may contribute to closing this: https://github.com/blitz-js/blitz/pull/687

**Comment by andreasasprou** [comment] 2020-06-15 05:34
https://www.loom.com/share/223f9b39f6c14366b1518f3ea3b533a5

**Comment by flybayer** [comment] 2020-06-15 06:51
`0.14.2-canary.0` is now published which includes the fix for `.git`

**Comment by ryardley** [comment] 2020-06-15 07:54
@andreasasprou can you please let us know if this helps you at all?

**Comment by flybayer** [comment] 2020-06-15 08:20
@gielcobben said it fixes the issue for him!

**Comment by andreasasprou** [comment] 2020-06-15 08:23
Same as what I showcase in 

> https://www.loom.com/share/223f9b39f6c14366b1518f3ea3b533a5

It stalls at some random file. Every time I run `blitz start` it stalls at a different point.

**Comment by flybayer** [comment] 2020-06-17 04:56
I just published `0.15.1-canary.0` with the possible fix from #697

**Comment by andreasasprou** [comment] 2020-06-17 06:45
Boom baby! Seems to fix my issue. @ryardley it seems you hypothesis around large number of files was the issue!

**Closed** 2020-06-17 08:06 UTC
Labels: kind/bug, priority/high, scope/server, status/ready-to-work-on

**Comment by flybayer** [comment] 2020-06-17 11:18
`0.15.1` now published with this fix
