### ISSUE TITLE
Focus issue?

### ISSUE THREAD

**Issue by juan-manuel-alberro** [blitz-js/blitz#2374] opened 2021-05-21 11:55 UTC
### What is the problem?

Hi,

Why every time the app gets the focus is calling the queries? I notice this with a paid service that I implemented (it has a limited quote of API calls), every time the app gets the focus it calls all the queries assigned to the component rendered.

I created a new app from the scratch and I can recreate the issue so is not only in my app

![issue](https://user-images.githubusercontent.com/7114488/119132633-db946a00-ba32-11eb-9eb4-5f6c22fd9284.gif)

In this case, only the `getCurrentUser` is available but if you have more queries, **all of them will be called** again.

### Paste all your error logs here:

No logs.

### Paste all relevant code snippets here:

Not needed, just create a new app and that's it.

### What are detailed steps to reproduce this?

1. You can recreate that doing <kbd>alt</kbd>+<kbd>tab</kbd> / <kbd>cmd</kbd>+<kbd>tab</kbd>, and even clicking in the app and in the Network tab like you can see at the end of the GIF.

### Run `blitz -v` and paste the output here:

```
Linux 4.19 | linux-x64 | Node: v14.16.1

blitz: 0.35.0 (global)
blitz: 0.35.0 (local)

  Package manager: yarn 
  System:
    OS: Linux 4.19 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 5.91 GB / 12.39 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1 
    blitz: 0.35.0 => 0.35.0 
    prisma: ~2.20 => 2.20.1 
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    typescript: ~4.2 => 4.2.4 
```

**Comment by lksnmnn** [comment] 2021-05-25 20:33
I think this is expected behaviour and an intentional feature. This irritated me once too, but you can read more about this here: https://blitzjs.com/docs/use-query#options

You can change the behaviour per query using the options: `refetchOnWindowFocus`

**Comment by kevinlangleyjr** [comment] 2021-05-27 14:06
It looks like this is documented and expected behavior here based on the documentation link from @lksnmnn. I think we're good to close this, but if you're still experiencing issues please file another issue @juan-manuel-alberro 🙂

**Closed by kevinlangleyjr** 2021-05-27 14:06 UTC
Labels: kind/bug, status/triage
