### ISSUE TITLE
Route manifest runtime errors

### ISSUE THREAD

**Issue by ghoshnirmalya** [blitz-js/blitz#2951] opened 2021-11-13 18:08 UTC
### What is the problem?

Getting the same error as https://github.com/blitz-js/blitz/issues/2865 while creating a new Blitz application.

### Paste all your error logs here:

```
app/pages/index.tsx (38:20) @ UserInfo

  36 | return (
  37 |   <>
> 38 |     <Link href={Routes.SignupPage()}>
     |                ^
  39 |       <a className="button small">
  40 |         <strong>Sign Up</strong>
  41 |       </a>
```

### Paste all relevant code snippets here:

```
TypeError: next_stdlib__WEBPACK_IMPORTED_MODULE_6__.Routes.SignupPage is not a function
```

### What are detailed steps to reproduce this?

1. npx blitz new blitz-app
2. ✔ You have the latest Blitz version
✔ Pick a new project's language · TypeScript
✔ Pick your new app template · full
✔ Install dependencies? · pnpm
✔ Pick a form library (you can switch to something else later if you want) · React Final Form
3. cd blitz-app
4. blitz dev

### Run `blitz -v` and paste the output here:

```
0.42.4
```

### Please include below any other applicable logs and screenshots that show your problem:

![image](https://user-images.githubusercontent.com/6391763/141654472-3d1a047f-cc80-4216-aa8e-998e7180f33b.png)

**Comment by flybayer** [comment] 2021-11-15 14:14
I believe is is a duplicate of https://github.com/blitz-js/blitz/issues/2935.

Let us know if it's not.

**Closed by flybayer** 2021-11-15 14:14 UTC
Labels: kind/bug, status/ready-to-work-on

**Comment by paulm17** [comment] 2022-06-23 10:14
I've got the same issue.  But I'm using yarn.
