### ISSUE TITLE
Generated scaffold for models with String ids fail

### ISSUE THREAD

**Issue by thebiglabasky** [blitz-js/blitz#490] opened 2020-05-10 14:41 UTC
### What is the problem?

When generating a scaffold for a model using a String id (e.g. `@id @default(cuid())`), the generated scaffold pages do a `parseInt` to convert the path param, instead of leaving it as is.

### Steps to Reproduce: 

1. Put together a model like

```
model Product {
  id            String   @id  @default(cuid())
  name          String
}
```

2. Generate a scaffold using `blitz generate all product`

3. Notice the `const id = parseInt(router?.query.id as string)` in both `pages/products/[id].tsx` and `pages/products/[id]/edit.tsx`

### Versions:

0.9.0

```
debug: local
debug: pkgPath: /Users/hlabas/Dev/blitzjs/kontext/node_modules/@blitzjs/cli 

macOS Catalina | darwin-x64 | Node: v13.14.0

blitz: 0.9.0 (global)
blitz: 0.9.0 (local)
```

### Supporting Documentation

I assume this requires to add some logic to allow [[id].tsx](https://github.com/blitz-js/blitz/blob/6eb07b688f8c46fd3defd6de91ae27d2f558cda4/packages/generator/templates/page/__id__.tsx#L8) and [edit.tsx](https://github.com/blitz-js/blitz/blob/6eb07b688f8c46fd3defd6de91ae27d2f558cda4/packages/generator/templates/page/__id__/edit.tsx#L8) templates to be adapted according to the specifics of the model.

**Comment by Blanen** [comment] 2020-05-10 21:26
Can I pick this up? 

If it's a string it shouldn't be left as it is but it should be url-decoded.

**Comment by Zeko369** [comment] 2020-05-11 08:53
Go ahead @Blanen

**Comment by MrLeebo** [comment] 2020-05-11 17:35
This isn't exactly a duplicate of https://github.com/blitz-js/blitz/issues/259 but when that issue is resolved it will likely resolve this as well.

**Comment by flybayer** [comment] 2020-05-12 14:18
@Blanen yeah, this will be taken care of by #259, but if you already have something for this specific case, we can still take it until we get #259 completed.

**Comment by flybayer** [comment] 2020-06-19 02:21
Closing this in favor of #259

**Closed by flybayer** 2020-06-19 02:21 UTC
Labels: kind/bug, status/assigned
