### ISSUE TITLE
Chakra UI's Radio component doesn't work properly in a Blitz app

### ISSUE THREAD

**Issue by frissonlabs** [blitz-js/blitz#1600] opened 2020-12-12 08:56 UTC
### What is the problem?

Tried to add Chakra UI's Radio buttons but clicking on a specific option doesn't immediately select it. The first click highlights the input and it requires a double-click to actually select it. 

I've tested this in vanilla next.js and create-react-app starters and it works properly (radio input gets selected on the first click). 

### Steps to Reproduce

1. Just add the Radio component from Chakra UI anywhere. I've created a repo using the Blitz starter app to demonstrate ([https://github.com/frissonlabs/blitz-chakra-test](https://github.com/frissonlabs/blitz-chakra-test))

### Versions

0.27.1 (and has affected previous version for at least the past 2 months as I've seen it back then as well)

### Other

N/A

**Comment by flybayer** [comment] 2020-12-15 22:04
Interesting, I've noticed this same issue with checkboxes in one of my Blitz apps with tailwind (not Chakra). So it may not be chakra related at all.

**Comment by dillonraphael** [comment] 2020-12-16 01:13
Are you using react-final-form or react-hook-form?

**Comment by frissonlabs** [comment] 2020-12-16 01:21
> Are you using react-final-form or react-hook-form?

react-hook-form

**Comment by frissonlabs** [comment] 2020-12-30 03:03
This issue still occurs even with the fix for [chakra-ui/chakra-ui#2842 ](https://github.com/chakra-ui/chakra-ui/issues/2842) which isn't the same issue

**Comment by imkrunal** [comment] 2020-12-31 11:56
The same issue happens with the checkbox component.

**Comment by malkomalko** [comment] 2021-01-10 23:07
👋🏻 I'd love to take a look at this issue as my first contribution if nobody else is taking a look at it.

**Comment by flybayer** [comment] 2021-01-11 20:04
@malkomalko that'd be great! 🙏

**Comment by malkomalko** [comment] 2021-01-13 01:49
Just dropping an update here that this is caused by blitz' experimental react versions.  You can see Chakra Radio components working by switching to version `17.0.1` and then adding the following to your blitz config.

```
{
  experimental: {
    reactMode: 'legacy'
  }
}
```

This is obviously not ideal, but will continue to look into finding a fix with the experimental usage.

**Comment by flybayer** [comment] 2021-01-13 22:55
Well, I've also done some more investigation and determined this is not an issue with React (vanilla controlled components work fine). Therefore it is a bug with react-final-form and with chakra.

There's already an open issue for react-final-form: https://github.com/final-form/react-final-form/issues/600

And an issue was opened for Chakra but closed without resolution: https://github.com/chakra-ui/chakra-ui/issues/2350

Since there's nothing we can do here in Blitz, I'll go ahead and close this.

**Closed by flybayer** 2021-01-13 22:55 UTC
Labels: kind/bug, priority/high, status/assigned

**Comment by anteprimorac** [comment] 2021-01-26 11:32
@flybayer this is an issue that causes this problems https://github.com/facebook/react/issues/18591

**Comment by flybayer** [comment] 2021-01-26 20:33
@anteprimorac oh nice find!

**Comment by anteprimorac** [comment] 2021-01-26 20:37
@flybayer I made a PR that applies workaround for chakra here https://github.com/chakra-ui/chakra-ui/pull/3165 so hopefully, soon it will work properly with concurrent mode. That's the only reason why I am using legacy react mode.

**Comment by chrisbull** [comment] 2021-02-01 01:39
@anteprimorac Looks like they merged your PR, but the issues still remain. 
Only when I set the flag does it work for blitz:
```
{
  experimental: {
     reactMode: "legacy"
  }
}
```
@flybayer:  I've tested extensively everything with create-next-app and ChakraUI works correctly, even if I'm using `react@experimental`. So something you're doing with the experimental settings is throwing things off. Any chance you can investigate what flags are doing this and if they are absolutely necessary? I really want to keep using blitz and chakra-ui... but this form stuff is pivotal. Also, it has nothing to do with react-final-form. I've created a test and not using it and the issues persist. Thanks in advance! (I'll share example project in a min)

**Comment by flybayer** [comment] 2021-03-25 19:31
Concurrent mode is now fixed for me as of react/react-dom `0.0.0-experimental-1fafac002` with react-final-form, so very likely Chakra is fixed too!

**Comment by thomasbroderick** [comment] 2021-03-28 18:49
I've been trying to add a Chakra Checkbox component to my Blitz app and I'm sad to report that even with the latest React experimental build and Chakra 1.4.0 that this error still persists. :(

**Comment by flybayer** [comment] 2021-03-29 19:01
@thomasbroderick ok, then set this and it should work

```
{
  experimental: {
     reactMode: "blocking"
  }
}
```

**Comment by flybayer** [comment] 2021-04-01 18:54
I just tested this myself and I can no longer reproduce 🤔 

```
    "blitz": "0.33.1",
    "react": "0.0.0-experimental-2c9fef32d",
    "react-dom": "0.0.0-experimental-2c9fef32d",
    "@chakra-ui/react": "1.4.2",
    "@emotion/react": "11.1.4",
    "@emotion/styled": "11.0.0",
```
