### ISSUE TITLE
Cancelling installer still outputs success message

### ISSUE THREAD

**Issue by dwightwatson** [blitz-js/blitz#904] opened 2020-08-18 03:08 UTC
### Steps to Reproduce

1. Start an installer, for example `blitz install chakra`.
2. When it outputs dependencies and asks you to press `ENTER` to install, press `control+C` (or otherwise cancel).
3. See the successful output:

```
🎉 The recipe for Chakra UI completed successfully! Its functionality is now fully configured in your Blitz app.
```

Cancelling a recipe before completion shouldn't display the success message - probably doesn't need any message at all.

### Versions

```
debug: blitzPkgPath: /Users/dwight/Sites/myapp/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/dwight/Sites/myapp/node_modules/@blitzjs/cli/lib/src/index.js 

macOS Catalina | darwin-x64 | Node: v14.8.0

blitz: 0.17.0 (global)
blitz: 0.17.1-canary.5 (local)
```

### Other

```
+––––––––––––––––––––––––––+
⎪   Add npm dependencies   ⎪
+––––––––––––––––––––––––––+
Chakra requires some other dependencies like emotion to work

Adding some shiny new dependencies.
If this list looks good, press ENTER to install.

Dependencies to be installed:
   📦 @chakra-ui/core@latest
   📦 @emotion/core@latest
   📦 @emotion/styled@latest
   📦 emotion-theming@latest

Dev Dependencies to be installed:

🎉 The recipe for Chakra UI completed successfully! Its functionality is now fully configured in your Blitz app.
```

**Comment by aem** [comment] 2020-08-18 15:08
Good catch. I'll address this in the upcoming revamp of the UX for the recipe runner

**Comment by flybayer** [comment] 2020-08-18 16:02
@aem sounds good. You can assign yourself if you decide to take an issue :)

**Comment by flybayer** [comment] 2020-11-14 22:43
The problem is [this line of code](https://github.com/blitz-js/blitz/blob/canary/packages/installer/src/recipe-executor.tsx#L37) runs for both success and failure.

**Comment by arjundubey-cr** [comment] 2020-11-29 03:06
@flybayer I would like to work on this issue. Can you please assign it to me?

**Comment by flybayer** [comment] 2020-12-01 17:09
@arjundubey-cr yes! Sorry for the long delay!

**Closed** 2020-12-17 21:11 UTC
Labels: good first issue, kind/bug, scope/installer, status/assigned
