### ISSUE TITLE
Type error in build

### ISSUE THREAD

**Issue by gielcobben** [blitz-js/blitz#2262] opened 2021-04-23 09:37 UTC
### What is the problem?

When I run `blitz build` I got an error.

### Paste all your error logs here:

```
info  - Checking validity of types...
Failed to compile.

../../node_modules/.blitz/index.d.ts:16:47
Type error: ',' expected.

  14 |   LoginPage(query?: ParsedUrlQueryInput): RouteUrlObject;
  15 |   InvitePage(query: { handle: string | number } & ParsedUrlQueryInput): RouteUrlObject;
> 16 |   Settings(query: { [...page: string | number } & ParsedUrlQueryInput): RouteUrlObject;
     |                                               ^
  17 |   Collections(query: { collectionId: string | number } & ParsedUrlQueryInput): RouteUrlObject;
  18 | }
error Command failed with exit code 1.
```

### Paste all relevant code snippets here:

```
...
```

### What are detailed steps to reproduce this?

1. Create a "catch all" route
2. Run `blitz build`

### Run `blitz -v` and paste the output here:

```
macOS | darwin-x64 | Node: v14.16.0

blitz: 0.34.3 (global)
blitz: 0.34.3 (local)

  Package manager: yarn
  System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 37.45 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/client: 2.21.2 => 2.21.2
    blitz: 0.34.3 => 0.34.3
    prisma: 2.21.2 => 2.21.2
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: 4.1.5 => 4.1.5
```

**Comment by flybayer** [comment] 2021-04-24 20:39
cc @Skn0tt

**Comment by flybayer** [comment] 2021-04-30 21:44
Duplicate of https://github.com/blitz-js/blitz/issues/2286 (that issue was created later, but has more detail, so closing this one)

**Closed by flybayer** 2021-04-30 21:44 UTC
Labels: kind/bug, status/ready-to-work-on
