### ISSUE TITLE
useQuery initialdata not being set correctly by QueryClient

### ISSUE THREAD

**Issue by Nfinished** [blitz-js/blitz#3010] opened 2021-11-30 17:26 UTC
### What is the problem?

dehydrated queryClient in getServerSideProps is not correctly rehydrating on the client, resulting in an empty cache and immediate fetch with a suspense state

### Paste all your error logs here:

no logs

### Paste all relevant code snippets here:

```tsx
import { Table, Tbody } from '@chakra-ui/react'
import {
  BlitzPage,
  dehydrate,
  getQueryKey,
  Head,
  invokeWithMiddleware,
  QueryClient,
  useQuery,
} from 'blitz'
import React, { Suspense } from 'react'
import spacetime from 'spacetime'

import AppLayout from 'app/core/layouts/AppLayout'
import NewProject from 'app/projects/components/NewProject'
import Project from 'app/projects/components/Project'
import getProjects from 'app/projects/queries/getProjects'

const createGetProjectsQuery = () => ({
  where: {
    endsAt: {
      gte: spacetime
        .now('utc')
        .subtract(1, 'day')
        .startOf('day')
        .toNativeDate(),
    },
  },
})

export const ProjectsTable = () => {
  const [projects] = useQuery(getProjects, createGetProjectsQuery())

  return (
    <>
      <Table variant="unstyled" width="100%">
        <Tbody>
          {projects.map((project, index) => (
            <Project key={index} {...project} />
          ))}
        </Tbody>
      </Table>
    </>
  )
}

const ProjectsPage: BlitzPage = () => {
  return (
    <>
      <Head>
        <title>Projects</title>
      </Head>
      <NewProject />

      <Suspense fallback={<div>Loading...</div>}>
        <ProjectsTable />
      </Suspense>
    </>
  )
}

ProjectsPage.authenticate = true
ProjectsPage.getLayout = (page) => <AppLayout>{page}</AppLayout>

export async function getServerSideProps(context) {
  const queryClient = new QueryClient()
  const queryKey = getQueryKey(getProjects, createGetProjectsQuery())

  await queryClient.prefetchQuery(queryKey, () =>
    invokeWithMiddleware(getProjects, createGetProjectsQuery(), context)
  )
  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}

export default ProjectsPage
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
blitz: 0.43.0 (local)

  Package manager: yarn
  System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 682.00 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.2 - /var/folders/34/c8tk0fm52hz6z0288x5npsp80000gp/T/yarn--1638293170726-0.422191689734861/node
    Yarn: 1.22.17 - /var/folders/34/c8tk0fm52hz6z0288x5npsp80000gp/T/yarn--1638293170726-0.422191689734861/yarn
    npm: 7.18.1 - ~/.asdf/installs/nodejs/16.4.2/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 3.5.0 => 3.5.0
    blitz: 0.43.0 => 0.43.0
    prisma: 3.5.0 => 3.5.0
    react: 18.0.0-alpha-5ca4b0433-20211020 => 18.0.0-alpha-5ca4b0433-20211020
    react-dom: 18.0.0-alpha-5ca4b0433-20211020 => 18.0.0-alpha-5ca4b0433-20211020
    typescript: ~4.4 => 4.4.4
    ```

**Comment by beerose** [comment] 2021-12-02 12:35
Could be related: https://github.com/blitz-js/blitz/issues/2370

**Comment by beerose** [comment] 2021-12-02 15:40
Hey @Nfinished! The problem is that you have dynamic data relying on the current time (`spacetime.now('utc')`), so the params are different in three places where you use them: 1) when retrieving query key, 2) when setting query client, 3) in the component when using `useQuery`. The hydration works correctly only when the query params are static. I'm going to close this issue as we can't do much about it.

**Comment by Nfinished** [comment] 2021-12-02 15:43
Hi, @beerose,  if you look at the next few lines

```
spacetime
        .now('utc')
        .subtract(1, 'day')
        .startOf('day')
        .toNativeDate()
```

you'll see that I'm effectively setting a floor with `.startOf('day')`. It'll be the same everywhere.

**Comment by beerose** [comment] 2021-12-02 18:57
Ah, sorry for missing that. Reopening it then.

**Closed** 2023-10-24 15:09 UTC
Labels: kind/bug, status/ready-to-work-on
