### ISSUE TITLE
Add required arguments to create query validation when using blitz generate all

### ISSUE THREAD

**Issue by agustif** [blitz-js/blitz#2257] opened 2021-04-21 20:18 UTC
### What do you want and why?
I would like zod validations to be auto-generated too
The more information the better!

so when running:
`blitz generate all photo name:string slug:string
```js
const CreatePhoto = z
  .object({
    name: z.string(),
    slug: z.string(),,
  })
  .nonstrict()
```

Instead of 

```js
const CreatePhoto = z
  .object({
    name: z.string()
  })
  .nonstrict()
```

So an app compiles after generator run, maybe this has been discarded bc bad idea idk, couldn't find any issue about it

**Comment by flybayer** [comment] 2021-04-24 20:31
This will be fixed by https://github.com/blitz-js/blitz/pull/2134!

**Comment by MrLeebo** [comment] 2021-07-15 01:30
Closing this as a duplicate of the linked PR

**Closed by MrLeebo** 2021-07-15 01:30 UTC
Labels: kind/duplicate, status/triage
