### ISSUE TITLE
Add `blitz export` command

### ISSUE THREAD

**Issue by lcswillems** [blitz-js/blitz#2026] opened 2021-03-01 12:26 UTC
### What do you want and why?

Next.js has a `next export` command to create a static website.

### Possible implementation(s)

I would like to have the same for Blitz.

**Comment by flybayer** [comment] 2021-03-01 17:33
Thanks @lcswillems, but closing as a duplicate of #2015

**Comment by flybayer** [comment] 2021-03-01 17:36
Actually nevermind, this is a separate issue :)

**Closed** 2021-03-16 18:28 UTC
Labels: kind/feature-change, status/assigned
