### ISSUE TITLE
Error: EPERM: operation not permitted, scandir 

### ISSUE THREAD

**Issue by hamidshoa** [blitz-js/blitz#1836] opened 2021-01-31 13:33 UTC
### What is the problem?
-Each time I need to start blitz, an error occurred. Code below shows that:

Error: EPERM: operation not permitted, scandir 'C:/Users/hamid/Desktop/Blitz/isgood/.blitz/caches/dev/.next/static/development'
    at Object.readdirSync (fs.js:955:3)
    at readdirWithFileTypes (C:\Users\hamid\Desktop\Blitz\isgood\node_modules\@nodelib\fs.scandir\out\providers\sync.js:16:33)     
    at Object.read (C:\Users\hamid\Desktop\Blitz\isgood\node_modules\@nodelib\fs.scandir\out\providers\sync.js:10:16)
    at SyncReader.scandirSync [as _scandir] (C:\Users\hamid\Desktop\Blitz\isgood\node_modules\@nodelib\fs.scandir\out\index.js:17:17)
    at SyncReader._handleDirectory (C:\Users\hamid\Desktop\Blitz\isgood\node_modules\@nodelib\fs.walk\out\readers\sync.js:28:34)   
    at SyncReader._handleQueue (C:\Users\hamid\Desktop\Blitz\isgood\node_modules\@nodelib\fs.walk\out\readers\sync.js:23:18)       
    at SyncReader.read (C:\Users\hamid\Desktop\Blitz\isgood\node_modules\@nodelib\fs.walk\out\readers\sync.js:15:14)
    at SyncProvider.read (C:\Users\hamid\Desktop\Blitz\isgood\node_modules\@nodelib\fs.walk\out\providers\sync.js:11:29)
    at ReaderSync.walkSync [as _walkSync] (C:\Users\hamid\Desktop\Blitz\isgood\node_modules\@nodelib\fs.walk\out\index.js:19:21)   
    at ReaderSync.dynamic (C:\Users\hamid\Desktop\Blitz\isgood\node_modules\@blitzjs\server\node_modules\fast-glob\out\readers\sync.js:13:21) {
  errno: -4048,
  syscall: 'scandir',
  code: 'EPERM',
  path: 'C:/Users/hamid/Desktop/Blitz/isgood/.blitz/caches/dev/.next/static/development'
}
### Steps to Reproduce

1.

### Versions
beta blitz version
```
output of `blitz --version --verbose`
```
Windows 10 | win32-x64 | Node: v12.18.4

blitz: 0.29.3 (global)
blitz: 0.29.3 (local)
Error: Blitz Error: Error: Command failed: wmic os get Caption

### Other
In the meanwhile I have two options to make blitz rerun again :
1-try running blitz many times until it's run again.
2- Go to  [.blitz] directory and remove the caches there, for example in my case ..caches/dev/.next/static/development, 

I don't know if I am the only person facing this issue!.

**Comment by flybayer** [comment] 2021-02-01 23:04
Wow that's a weird one! Thanks for the report.

Probably to reproduce we need to use `chmod` in the terminal to change the file permissions

**Comment by Extra-Extra-Dev** [comment] 2021-02-15 18:07
Reporting I got this a few times just now while chatting with flybayer. Then with no intervention on my part but rerunning "npx blitz build" a 3rd time was able to bypass the error .

**Comment by flybayer** [comment] 2021-02-15 18:18
Related: https://github.com/blitz-js/blitz/issues/1943

**Comment by markhughes** [comment] 2021-02-17 22:46
This error here:

```
errno: -4048,
syscall: 'scandir',
code: 'EPERM',
```

Is related to locked files. But this may not be blitz specific...

@Extra-Extra-Dev are you using vscode? If so, does the issue happen if you close vscode? 

I believe #1943 and #1944 is caused by the same issue.

**Comment by markhughes** [comment] 2021-02-18 21:36
FYI: those with a similar issue, an easy solution is to close vscode. But you can also [configure vscode to hide node_moules](https://stackoverflow.com/a/30142299).

**Comment by Extra-Extra-Dev** [comment] 2021-02-19 00:03
> FYI: those with a similar issue, one solution is to close vscode. But you can also [configure vscode to hide node_moules](https://stackoverflow.com/a/30142299).

Ohhhhhhhh.  Hiding Node_modules may help? Interesting.  
But yes... closeing and opening resolves it.. but of course it leaves permissions of unknown files in an unknown state for the next pass ( which Is why i've been reporting it so it's a known issue).

now.. need to find out how to hide Node_modules to see if that helps! it's a constant problem!

**Comment by flybayer** [comment] 2021-02-19 02:18
Hey y'all, please update to https://github.com/blitz-js/blitz/releases/tag/v0.30.1 and see if this is fixed or not.

**Comment by markhughes** [comment] 2021-02-19 04:48
I've recently moved to a windows machine (from work for WFH) and I find that most things in node_modules and the .blitz .next folders gets "locked" by vscode, so I fall into that issue a lot :( 

@flybayer I'll try that soon and see if it resolves the issue!

**Comment by Extra-Extra-Dev** [comment] 2021-02-23 01:08
I've not been doing as much work this past few days (been focusing on docker builds). But I've noticed a little less trouble.  I still report back when I get back in to heavier production.

**Comment by flybayer** [comment] 2021-02-25 19:16
Going to close because it should be fixed.

And if not fixed now, it will be fixed by  https://github.com/blitz-js/blitz/discussions/1990

**Closed by flybayer** 2021-02-25 19:16 UTC
Labels: kind/bug, os/windows, status/ready-to-work-on
