### ISSUE TITLE
enhanced ui codegen

### ISSUE THREAD

**Issue by Vandivier** [blitz-js/blitz#3628] opened 2022-07-28 01:54 UTC
### What do you want and why?

when i generate a model, have the UI form be more intelligently created. this is to save developer time.

### Possible implementation(s)

detect whether a `blitz g all foobar` is using supported properties/fields like a string field and if so, append the appropriate HTML/jsx/tsx/etc code into the appropriate UI components such as adding a text notes field to the create form for the following example model:
`blitz g all foobar name:string notes:string`

**Comment by beerose** [comment] 2022-07-28 12:49
Closing as a duplicate of https://github.com/blitz-js/blitz/issues/2038

Let us know if there's anything else you'd like to see supported in codegen that isn't mentioned in https://github.com/blitz-js/blitz/issues/2038

**Closed by beerose** 2022-07-28 12:49 UTC
Labels: status/triage
