### ISSUE TITLE
Throwing error within NextJS getServerSideProps is not caught by ErrorBoundary

### ISSUE THREAD

**Issue by mbrookson** [blitz-js/blitz#3819] opened 2022-09-05 21:02 UTC
### What is the problem?

Using `getServerSideProps` is a huge benefit of using NextJS, but there's currently an issue within Blitz where throwing an error inside the `getServerSideProps` function is not reaching the `ErrorBoundary` on the client.

It means the error shown is the standard uncaught error exception for the development environment rather than being gracefully handled by the error boundary.

### Paste all your error logs here:

```
error - app/users/queries/getUser.ts (31:10) @ eval
error - NotFoundError: User not found
    at eval (webpack-internal:///./app/users/queries/getUser.ts:41:15)
    at async /Users/matthewbrookson/Code/test-project/node_modules/@blitzjs/rpc/dist/index-server.cjs:29:20
    at async eval (webpack-internal:///./pages/users/[id].tsx:30:18)
    at async eval (webpack-internal:///./node_modules/@blitzjs/next/dist/index-server.cjs:44:22)
    at async Object.renderToHTML (/Users/matthewbrookson/Code/test-project/node_modules/next/dist/server/render.js:490:20)
    at async doRender (/Users/matthewbrookson/Code/test-project/node_modules/next/dist/server/base-server.js:908:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/Users/matthewbrookson/Code/test-project/node_modules/next/dist/server/base-server.js:1013:28)
    at async /Users/matthewbrookson/Code/test-project/node_modules/next/dist/server/response-cache.js:69:36

```

### Paste all relevant code snippets here:

```tsx
import getUser from 'app/users/queries/getUser'

export const getServerSideProps = gSSP<ServerProps, Params>(async ({ params, ctx }) => {
  const id = parseInt(params!.id)
  const user = await getUser({ id }, ctx)
  return { props: { user } }
})

// app/users/queries/getUser.ts
export default resolver.pipe(resolver.zod(GetUser), async (input) => {
  const { id } = input

  const user = await db.user.findFirst({ where: { id } })

  if (!user) {
    throw new NotFoundError("User not found")
  }

  return form
})
```

Take this snippet for example. If you throw the `NotFoundError` within a Blitz query and use `useQuery` within a client component it works and displays the expected Blitz `ErrorComponent`:
![image](https://user-images.githubusercontent.com/20131783/188511633-71dcf7ca-bde6-4bab-9b56-2db546503b07.png)

However when you use this query _within_ the `getServerSideProps` function and the `NotFoundError` gets thrown, it just renders the following error message:
![image](https://user-images.githubusercontent.com/20131783/188511831-4d5a9a8d-5a03-4bbb-bdc0-46ee4cace3d1.png)

### What are detailed steps to reproduce this?

1. Create a simple query as per code snippet that throws an error
2. Export a page component
3. Export a simple `getServerSideProps` function that calls the query function causing the error

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.3 (global)
Blitz version: 2.0.0-beta.3 (local)
macOS Monterey | darwin-arm64 | Node: v16.17.0


 Package manager: npm

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 70.28 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /opt/homebrew/opt/node@16/bin/node
    Yarn: Not Found
    npm: 8.15.0 - /opt/homebrew/opt/node@16/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.3 => 2.0.0-beta.3 
    @blitzjs/next: 2.0.0-beta.3 => 2.0.0-beta.3 
    @blitzjs/rpc: 2.0.0-beta.3 => 2.0.0-beta.3 
    @prisma/client: 4.0.0 => 4.0.0 
    blitz: 2.0.0-beta.3 => 2.0.0-beta.3 
    next: 12.2.5 => 12.2.5 
    prisma: 4.3.1 => 4.3.1 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.5.3 => 4.8.2 
```

**Comment by dillonraphael** [comment] 2022-09-06 18:07
This is expected behaviour. When throwing an error on the server, you're going to get the server error.

Though there is a solution that would require a little manual work.

Inside your query you can do this:
```ts
export default resolver.pipe(resolver.zod(GetUser), async (input) => {
  const { id } = input

  const user = await db.user.findFirst({ where: { id } })

  if (!user) {
    const userError = new NotFoundError("User not found")
    return {
      error: userError.statusCode
    }
  }

  return form
})
```

Then inside `gSSP`

```ts
export const getServerSideProps = gSSP<ServerProps, Params>(async ({ params, ctx }) => {
  const id = parseInt(params!.id)
  const user = await getUser({ id }, ctx)
  if("error" in user) {
    return { props: { error: user.error}}
  } else {
    return { props: { user }}
  }
})
```
And just update your generic for `gSSP`.

You can also create a util function to do this and catch server errors in `_app.tsx` by following this: https://github.com/vercel/next.js/discussions/12652#discussioncomment-90145

**Comment by mbrookson** [comment] 2022-09-06 19:48
Interesting. Thanks for the response and workaround.

Why is this expected behaviour though? In terms of what's happening, in both scenarios the work is being performed on the server. Therefore I'd expect the behaviour to be the same, whether it's a call to the API via a Blitz query from the client, or on initial page load via `getServerSideProps`.

**Comment by MrLeebo** [comment] 2022-09-11 16:08
While the function of getServerSideProps always runs on the server, the context for how it gets presented to the user is different depending on if it's a full page load or a client side navigation.

When you request a page in your browser, the first thing that gets loaded is the HTML document. This document contains references to the bundled script files that allow components to be interactive, including Error Boundary components like the one in the app template.

After the initial page is loaded, links between pages inside client side routing to avoid doing the full page load again; they may load a bundle containing components that are needed for the new page, and they'll load a JSON payload containing the data from getServerSideProps, but otherwise they are reusing the app components you've already mounted. 

So an error while navigating between pages can activate an error boundary because the app has already been loaded into the browser on the initial page load. But an error ON the initial page load? ...No app is mounted, meaning there's no Error Boundary component. 

The full page load also doesn't need to fetch the getServerSideProps data as a separate JSON payload because it's already embedded into the document's HTML. So the data gets loaded in different ways depending on if it's an initial page load or a navigation.

During an error, rendering the requested page has failed, so you can't use that page to provide an Error Boundary. You'd need to designate a new page to render. You'd want that page to be simpler than the one you originally tried, because you don't want it to just throw an error again. Especially if the error is coming from a common dependency like a database connection that has failed. So you want to have a separation between the error page and your normal app middleware.  That's basically what the server error page is.

**Comment by mbrookson** [comment] 2022-09-11 16:12
Aha! Understood. Thanks for the detailed explanation - makes total sense 👍

**Comment by beerose** [comment] 2022-09-15 18:39
Closing this issue as it seems to be resolved after following the discussion above. Feel free to reopen if it's not.

**Closed by beerose** 2022-09-15 18:39 UTC
Labels: kind/bug, status/triage
