### ISSUE TITLE
Running Blitz generate with a default value fails

### ISSUE THREAD

**Issue by doeixd** [blitz-js/blitz#1110] opened 2020-09-18 15:52 UTC
### What is the problem?
I tried to run 

`blitz g all post content:string likes:int:default[0]`

and I get the error:

`no matches found: likes:int:default[0]`

That error appears regardless of what I put in the brackets, or what type the field is.

### Steps to Reproduce

1. install blitz
2. create new project
3. `blitz g all post content:string likes:int:default[0]`

### Versions

```

debug: blitzPkgPath: /home/i3/Projects/Jobs/node_modules/blitz/dist/index.js
debug: cliPkgPath: /home/i3/Projects/Jobs/node_modules/@blitzjs/cli/lib/src/index.js 

Linux 5.8 | linux-x64 | Node: v14.11.0

blitz: 0.22.1 (global)
blitz: 0.22.1 (local)

  Package manager: yarn 
  System:
    OS: Linux 5.8 Arch Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 3.73 GB / 15.30 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.11.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.7 - /usr/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.7.1 => 2.7.1 
    @prisma/client: 2.7.1 => 2.7.1 
    blitz: 0.22.1 => 0.22.1 
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    typescript: 4.0.2 => 4.0.2 
```

**Comment by flybayer** [comment] 2020-09-18 22:12
Hey, yeah that's a known issue 👉 https://github.com/blitz-js/blitz/issues/724

Will close this as a duplicate of that one.

**Closed by flybayer** 2020-09-18 22:12 UTC
Labels: kind/duplicate, status/triage
