### ISSUE TITLE
Installing chakra-ui throws a `Invalid hook call` error.

### ISSUE THREAD

**Issue by daganomri** [blitz-js/blitz#1960] opened 2021-02-18 18:06 UTC
### What is the problem?
I'm trying to install the chakra-ui recipe on a brand new project and after trying to install the dependencies it throws a `Invalid hook call` error.
```
  ERROR  Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
        1. You might have mismatching versions of React and the renderer (such as React DOM)
        2. You might be breaking the Rules of Hooks
        3. You might have more than one copy of React in the same app
        See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

 - 1. You might have mismatching versions of React and the renderer (such as React DOM)
 - 2. You might be breaking the Rules of Hooks
 - 3. You might have more than one copy of React in the same app
 - See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
 - resolveDispatcher (/tmp/blitz-recipe-blitz-js-blitz/node_modules/@blitzjs/installer/node_modules/react/cjs/react.development.js:1488:13)
 - Proxy.useReducer (/tmp/blitz-recipe-blitz-js-blitz/node_modules/@blitzjs/installer/node_modules/react/cjs/react.development.js:1528:20)
 - RecipeRenderer (/tmp/blitz-recipe-blitz-js-blitz/node_modules/@blitzjs/installer/src/recipe-renderer.tsx:157:35)
 - renderWithHooks (/tmp/blitz-recipe-blitz-js-blitz/node_modules/ink/node_modules/react-reconciler/cjs/react-reconciler.development.js:6036:18)
 - mountIndeterminateComponent (/tmp/blitz-recipe-blitz-js-blitz/node_modules/ink/node_modules/react-reconciler/cjs/react-reconciler.development.js:8570:13)
 - beginWork$1 (/tmp/blitz-recipe-blitz-js-blitz/node_modules/ink/node_modules/react-reconciler/cjs/react-reconciler.development.js:9938:16)
 - Object.invokeGuardedCallbackImpl (/tmp/blitz-recipe-blitz-js-blitz/node_modules/ink/node_modules/react-reconciler/cjs/react-reconciler.development.js:11563:10)
 - invokeGuardedCallback (/tmp/blitz-recipe-blitz-js-blitz/node_modules/ink/node_modules/react-reconciler/cjs/react-reconciler.development.js:11740:31)
 - beginWork$$1 (/tmp/blitz-recipe-blitz-js-blitz/node_modules/ink/node_modules/react-reconciler/cjs/react-reconciler.development.js:15778:7)
 - performUnitOfWork (/tmp/blitz-recipe-blitz-js-blitz/node_modules/ink/node_modules/react-reconciler/cjs/react-reconciler.development.js:14696:12)
```
### Steps to Reproduce
1. run command `blitz new <project-name>`
2. cd into newly created <project-name> folder
3. run `blitz install chakra-ui`
### Versions
```
debug: blitzPkgPath: /home/user/Projects/blitz-test/node_modules/blitz/dist/index.js
debug: cliPkgPath: /home/user/Projects/blitz-test/node_modules/@blitzjs/cli/lib/src/index.js 

Linux 4.19 | linux-x64 | Node: v15.4.0

blitz: 0.30.0 (global)
blitz: 0.30.0 (local)

  Package manager: npm 
  System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 8.16 GB / 12.44 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 15.4.0 - ~/.nvm/versions/node/v15.4.0/bin/node
    Yarn: Not Found
    npm: 7.3.0 - ~/.nvm/versions/node/v15.4.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.17 => 2.17.0 
    blitz: 0.30.0 => 0.30.0 
    prisma: ~2.17 => 2.17.0 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.1.5 => 4.1.5 
```
### Other
I've also tried running blitz dev to see if the recipe needed the .blitz directory. The error still happens.

**Comment by dmvinson** [comment] 2021-02-19 15:36
Same issue as #1953, try using yarn

**Comment by piotrski** [comment] 2021-02-19 17:56
We are trying to call `npm add` instead of `npm install`. Should be pretty easy to fix.

**Comment by MrLeebo** [comment] 2021-02-19 19:11
Closing this as a duplicate of #1953, feel free to comment there if you have additional information

**Closed by MrLeebo** 2021-02-19 19:11 UTC
Labels: kind/bug, kind/duplicate, status/ready-to-work-on
