### ISSUE TITLE
blitz db seed not working for me

### ISSUE THREAD

**Issue by mhmdAljefri** [blitz-js/blitz#1354] opened 2020-10-18 15:58 UTC
### What is the problem?

Cannot run seeds command on blitz cli. once I run this I got this message below and I'm sure I have the `seeds.ts` file 

Couldn't import default from db/seeds.ts or db/seeds/index.ts file

### Steps to Reproduce

1. `blitz new appName # with low-speed internet connections
2. `cd appName && yarn
3. blitz db seed

### Versions

Linux 5.4 | linux-x64 | Node: v12.18.4

blitz: 0.24.3 (global)
blitz: 0.24.3 (local)

  Package manager: yarn 
  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 469.46 MB / 7.53 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.x => 2.9.0 
    @prisma/client: 2.x => 2.9.0 
    blitz: latest => 0.24.3 
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    typescript: 4.x => 4.0.3 

### Other

![Couldn't import default from db/seeds.ts or db/seeds/index.ts file
error message](https://user-images.githubusercontent.com/15002714/96373014-83cb1300-1172-11eb-9107-43ead1731b09.png)

**Comment by tundera** [comment] 2020-10-18 18:27
I noticed this wasn't working for me either the other day too

**Comment by patosullivan** [comment] 2020-10-18 19:03
Yep, seeing the same issue.

**Comment by flybayer** [comment] 2020-10-18 21:26
Duplicate of #1221, so closing this one. Subscribe to that issue for updates :)

**Closed by flybayer** 2020-10-18 21:26 UTC
Labels: status/triage
