### ISSUE TITLE
Prisma can't connect to database after 30.0 update.

### ISSUE THREAD

**Issue by karimsx** [blitz-js/blitz#1982] opened 2021-02-21 06:13 UTC
**What is the problem?**

Prisma can't connect to postgresql database after 30.0 update.

Error: Invalid `prisma.user.create()` invocation: connect ECONNREFUSED ::1:46113

Each time, the connection port `46113` is differents, even if i specified the port in `DATABASE_URL`

**What are detailed steps to reproduce this?**

1. setup database to postgresql or any database(tested sqlite too) and create DATABASE_URL env variable :

```DATABASE_URL="postgresql://karims:karims=@localhost:5432/main"```

when there is any db access, for example generated signup/login form always trigger this error. i have the version 0.29 and its working great in my git repo 

**Solution**

Downgrading prisma to 2.14 make it work, so i guess its a prisma issue?

**Run `blitz -v` and paste the output here:**

```
Linux 5.10 | linux-x64 | Node: v14.12.0

blitz: 0.30.2 (global)
blitz: 0.30.2 (local)

  Package manager: yarn 
  System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 4.40 GB / 15.62 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.12.0 - ~/.nvm/versions/node/v14.12.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.12.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.12.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.17 => 2.17.0 
    blitz: 0.30.2 => 0.30.2 
    prisma: ~2.17 => 2.17.0 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.1.5 => 4.1.5 

```

**Comment by flybayer** [comment] 2021-02-22 21:23
Looks like an issue connecting to your database server. Are you sure it's running and running on port 5432?

**Comment by karimsx** [comment] 2021-02-23 08:06
Hmm, yes actually i downgraded my version to blitz 0.29 and its working correctly without any modification in database, is there a way to show more logs about the error?

**Comment by flybayer** [comment] 2021-02-23 20:17
@karimsx yeah you can enable more prisma logging: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/logging

**Comment by MrLeebo** [comment] 2021-03-19 04:38
I'm closing this issue because it seems to have gone quiet. Without those additional logs there's nothing to follow up on and I'm not observing any issue connecting to a database. Feel free to re-open / comment again if you have a way to reproduce this issue.

**Closed by MrLeebo** 2021-03-19 04:38 UTC
Labels: kind/bug, status/triage
