### ISSUE TITLE
nextjs (app router) fails on vercel 

### ISSUE THREAD

**Issue by authentiqdigital** [blitz-js/blitz#4315] opened 2024-03-25 07:58 UTC
### What is the problem?

Repo: https://github.com/authentiqagency/next-blitz-auth.git

Project is running locally, with build and serve. But deployed on vercel, it just works for me with blitz 2.0.4 / next 13.5.4

Simple **working** example, deployed on vercel, first commit "working" with 
**"blitz 2.0.4; next 13.5.4"**

Vercel deploys **failed** with following configurations

**"blitz 2.0.5; next 13.5.4"**
Blitz Error-Page Showing.
vercel log:
`Error: Usage of `useAuthenticatedBlitzContext` is supported only in next.js 13.0.0 and above. Please upgrade your next.js version.
    at /var/task/.next/server/chunks/303.js:474:18140
    at Generator.next (<anonymous>)
    at /var/task/.next/server/chunks/303.js:474:15871
    at new Promise (<anonymous>)
    at __async$1 (/var/task/.next/server/chunks/303.js:474:15618)
    at getBlitzContext (/var/task/.next/server/chunks/303.js:474:17625)
    at /var/task/.next/server/chunks/303.js:474:18593
    at Generator.next (<anonymous>)
    at /var/task/.next/server/chunks/303.js:474:15871
    at new Promise (<anonymous>)`

**"blitz 2.0.5; next 14.1.4"**
500-Internal Server Error. App not showing
`[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '298443861',
  page: '/de'
}`

### Paste all your error logs here:

```
Error: Usage of `useAuthenticatedBlitzContext` is supported only in next.js 13.0.0 and above. Please upgrade your next.js version.
    at /var/task/.next/server/chunks/303.js:474:18140
    at Generator.next (<anonymous>)
    at /var/task/.next/server/chunks/303.js:474:15871
    at new Promise (<anonymous>)
    at __async$1 (/var/task/.next/server/chunks/303.js:474:15618)
    at getBlitzContext (/var/task/.next/server/chunks/303.js:474:17625)
    at /var/task/.next/server/chunks/303.js:474:18593
    at Generator.next (<anonymous>)
    at /var/task/.next/server/chunks/303.js:474:15871
    at new Promise (<anonymous>)

[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '298443861',
  page: '/de'
}
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
PASTE_HERE (leave the ``` marks)
```

**Comment by gengjiawen** [comment] 2024-03-26 10:03
duplicate of https://github.com/blitz-js/blitz/issues/4303

**Closed** 2024-04-02 12:29 UTC
Labels: kind/bug, status/triage
