### ISSUE TITLE
need better__internal_rpcHandler err surfacing

### ISSUE THREAD

**Issue by Vandivier** [blitz-js/blitz#4022] opened 2022-12-29 16:48 UTC
### What is the problem?

given a simple syntax error in a mutation, the system errors obscurely with a reference to `__internal_rpcHandler`. As a developer, this is not informative or actionable so I'd like additional information surfaced.

### Paste all your error logs here:

```
wait  - compiling /_error (client and server)...
error - ./app/admin/queries/getDemoDataIndicator.ts
Error:
  x Expected ',', got '__internal_rpcHandler'
    ,----
 21 | __internal_rpcHandler._resolverName = 'getDemoDataIndicator'
    : ^^^^^^^^^^^^^^^^^^^^^
    `----

Caused by:
    0: failed to process input file
    1: Syntax Error
```

### Paste all relevant code snippets here:

[after deleting the actual implementation and writing a toy implementation as a troubleshooting strategy...]
```
export default resolver.pipe(resolver.authorize(), async (_ = null) => {
    return false
}
```

### What are detailed steps to reproduce this?

1. u can make a new migration using the resolver pipe pattern and delete the final paren and you will get this error
2. you can also make any number of syntax errors and get the same error - so it's a highly ambiguous error. further, you can make a syntax error in module B and receive this error in mutation A if it imports module B

### Run `blitz -v` and paste the output here:

```
$ blitz --version
Blitz version: 2.0.0-beta.19 (global)
Blitz version: 2.0.0-beta.19 (local)
Windows 10 | win32-x64 | Node: v19.3.0


 Package manager: npm

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 1.38 GB / 7.88 GB
  Binaries:
    Node: 19.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.8.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.19 => 2.0.0-beta.19
    @blitzjs/next: 2.0.0-beta.19 => 2.0.0-beta.19
    @blitzjs/rpc: 2.0.0-beta.19 => 2.0.0-beta.19
    @prisma/client: 4.6.0 => 4.6.0
    blitz: 2.0.0-beta.19 => 2.0.0-beta.19
    next: 12.2.5 => 12.2.5
    prisma: 4.6.0 => 4.6.0
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.8.4 => 4.9.4
```

**Comment by Vandivier** [comment] 2022-12-29 17:23
i get the same error for another cause (not a syntax error) as demonstrated below:

works:
```
const getDemoDataIndicator = async (_ = null, ctx: Ctx): Promise<boolean> => {
  if (ctx.session.role !== RoleEnum.ADMIN) throw new AuthorizationError()

  const demoTag = await db.tag.findFirst({ where: { tagName: { endsWith: DEMO_DATA_TAG_NAME } } })

  return demoTag !== null
}

export default getDemoDataIndicator
```

errors (via `__internal_rpcHandler is not defined`):
```
export const getDemoDataIndicator = async (_ = null, ctx: Ctx): Promise<boolean> => {
  if (ctx.session.role !== RoleEnum.ADMIN) throw new AuthorizationError()

  const demoTag = await db.tag.findFirst({ where: { tagName: { endsWith: DEMO_DATA_TAG_NAME } } })

  return demoTag !== null
}
```

so the difference here is whether I export the entity as a default export. that's something we can lint and show to the developer. this is an unexpected blitz behavior so we should inform the developer. what I would expect in a generic TS env is that either approach works fine as long as I import it correctly.

**Comment by dillonraphael** [comment] 2022-12-29 19:29
Yup @Vandivier there is an open issue for this here https://github.com/blitz-js/blitz/issues/3994. Will close this since it's a duplicate. The issue is ready for someone to work on it.

**Closed by dillonraphael** 2022-12-29 19:29 UTC
Labels: kind/bug, status/triage
