### ISSUE TITLE
Triggering logging out on a page that uses queries that require authentication leads to an unhandled failed authentication exception

### ISSUE THREAD

**Issue by AndriusBartulis** [blitz-js/blitz#1935] opened 2021-02-14 16:04 UTC
### What is the problem?
Triggering logging out on a page that uses queries that require authentication leads to an unhandled failed authentication exception. This is using `Page.authenticate = {redirectTo: "/login"}` on the page.

### Steps to Reproduce

1. Use `Page.authenticate = {redirectTo: "/login"}` on a BlitzPage.
2. Use useQuery with any query that checks for an authenticated user. I am using resolver.authorize() to force this in my query.
3. Add a logout button. I use an onClick handler of `async () => { await logoutMutation() }` where the logout mutation is the one that comes with Blitz.
4. Login, visit the page, refresh the page (as this error does not occur if you are redirected to that page using ?next= from login page which is also strange), click logout. You will be correctly redirected to the /login page once you click the logout button, but also see "Unhandled Runtime Error - AuthenticationError: You must be logged in to access this" error flash up as when you click the Logout button, the useQuery tries to refetch the data, and it does so faster than the page can navigate away from the page.

### Versions
0.30.0-canary.13
```
Linux 4.19 | linux-x64 | Node: v14.15.1

blitz: 0.30.0-canary.5 (global)
blitz: 0.30.0-canary.13 (local)

  Package manager: npm
  System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 10.50 GB / 12.37 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: Not Found
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.16 => 2.16.0
    blitz: 0.30.0-canary.13 => 0.30.0-canary.13
    prisma: ~2.16 => 2.16.0
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    typescript: 4.1.3 => 4.1.3
```

### Other
As you can see in the XHR requests, after the logout mutation is called, the 2 queries still fire, when they should not. In some way we need to ensure the login mutation finishes, and the `Page.authenticate` code navigates to the specified page before the queries on the page have a chance to refetch.

![image](https://user-images.githubusercontent.com/6200977/107881720-869a0280-6edd-11eb-9f76-ec8c2b765fc5.png)

**Comment by flybayer** [comment] 2021-02-15 18:12
@AndriusBartulis I think the solution is to also manually redirect after the logout mutation as shown below. This code is working for me. Can you try it and confirm?

```tsx
import {useSession, useRouter, useMutation, Head} from "blitz"
import logout from "app/auth/mutations/logout"

export default function Layout({title, children}: {title?: string; children: React.ReactNode}) {
  const session = useSession({suspense: false})
  const router = useRouter()
  const [logoutMutation] = useMutation(logout)
  return (
    <>
      <Head>
        <title>{title || "__name__"}</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {session.userId && (
          <button
            onClick={async () => {
              await logoutMutation()
              router.push("/")
            }}
          >
            Logout
          </button>
        )}
        <div>{children}</div>
      </div>
    </>
  )
}

```

**Comment by AndriusBartulis** [comment] 2021-02-15 23:25
@flybayer Just tried this. Just adding `router.push("/")` didn't fix the problem, but your example showed` {suspense: false} `being passed to queries, and doing that instead of using suspense indeed fixed the issue. I guess some concurrency issue here with the useQuery refetching data when during or just after the logout mutation triggering. 

So the actual issue is not quite solved, but I did find a workaround by not using suspense, which is fine for my use case.

**Comment by flybayer** [comment] 2021-02-16 16:16
Hmm. In this case only `useSession` has suspense:false. The actual queries are using suspense

**Comment by AndriusBartulis** [comment] 2021-02-16 17:14
It's probably something I misconfigured somewhere else then. Doesn't look like anyone else is having this issue. Shall we close this for now?

**Comment by flybayer** [comment] 2021-02-16 17:30
Let's leave it open for some more investigation

**Comment by mbrookson** [comment] 2021-04-28 22:30
I'm currently getting a similar issue to this. Logout immediately revokes the session, which I assume is causing a render pass. It is therefore calling a query which tries to use the authenticated userId from session context, which is now null after logging out.

It's fixable by having a session/current user check in each page, but that seems a little dirty to have littered all over the place.

I noticed there is a `redirectAuthenticatedTo` property on the default `LoginPage`. Perhaps it would be good to introduce a `redirectUnauthenticatedTo` as well? Then if the session changes it should read that and check the auth status under the hood when rendering a page? Just an idea without much understanding of the internals so far.

**Comment by lksnmnn** [comment] 2021-05-06 21:08
I am having the same issue (I think). I made a minimal example based on a new blitz 0.34.3 app.
Steps to reproduce:

1. Register / Login
2. Go to authentication protected page /private
3. Click the logout button
4. Dont get redirected to the homepage

Instead of the redirect, the queries run again (I only have a non failing useCurrentUser hook here, but the issue would be the same as above, when you have queries that enfore authorization).

MFE repo: https://github.com/lksnmnn/blitz-logout-routing-issue

The essential action:

```
      <button
        onClick={async () => {
          await logoutMutation()
          router.push("/")
        }}
      >
        Logout
      </button>
```

**Comment by noxify** [comment] 2021-05-12 20:42
@lksnmnn had the same challenge.

Until there is a permanent solution like `redirectUnauthenticatedTo`, you can add a 

`router.push('/login')` inside the `else`.

Example:

```ts
  if (currentUser) {
    return (
      <>
        <button
          className="button small"
          onClick={async () => {
            await logoutMutation()
            router.push("/login")
          }}
        >
          Logout
        </button>

        <div>
          User id: <code>{currentUser.id}</code>
          <br />
          User role: <code>{currentUser.role}</code>
        </div>
      </>
    )
  } else {
    router.push('/login')
  }
```

**Comment by lksnmnn** [comment] 2021-05-12 21:04
Alright, that fixes the issue for now. Thank you.

I might attempt to debug why the the queries fire before routing to "/login. I naively would expect the above code to do the mutation and then immediately route.

**Comment by benbender** [comment] 2021-05-16 23:01
My solution ftm: 
````
<button
    className="w-full uppercase"
    onClick={async () => {
        await router
        .push(Routes.HomePage())
        .finally(() => logoutMutation());
    }}
    >
    <Menu.Item as="span" className={resolveClass}>
        Log Out
    </Menu.Item>
</button>
````

**Comment by lksnmnn** [comment] 2021-05-17 06:36
> My solution ftm:
> 
> ```js
> <button
>     className="w-full uppercase"
>     onClick={async () => {
>         await router
>         .push(Routes.HomePage())
>         .finally(() => logoutMutation());
>     }}
>     >
>     <Menu.Item as="span" className={resolveClass}>
>         Log Out
>     </Menu.Item>
> </button>
> ```

Neat! I am adding this right now. 
It does feel unituitive but it solves the issue for me 👍 .

**Comment by benbender** [comment] 2021-05-17 08:40
@lksnmnn It should also work with `.then()` instead of `.finally()`. You could try smth like:

```js
    onClick={async () => {
        await deleteAccountMutation()
        .then(() => router.push(Routes.HomePage())
        .then(() => logoutMutation())
        .catch((error) { console.error(error); });
    }}
```

**Comment by remjx** [comment] 2021-05-19 14:36
The `router.push(Routes.HomePage)` before `logoutMutation()` workaround works for me after I disabled all redirect functionality on the homepage.

However the console is still logging these errors:

in `/node_modules/react-query/es/core/mutation.js`
```
CancelledError {revert: undefined, silent: undefined}
```

in `/node_modules/next/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js`:
```
Uncaught (in promise) 
CancelledError {revert: undefined, silent: undefined}
asyncGeneratorStep    @    asyncToGenerator.js:6
_throw    @    asyncToGenerator.js:29
Promise.then (async)        
asyncGeneratorStep    @    asyncToGenerator.js:13
_next    @    asyncToGenerator.js:25
(anonymous)    @    asyncToGenerator.js:32
(anonymous)    @    asyncToGenerator.js:21
_handleLogout    @    log-out-button.tsx:6
handleLogout    @    log-out-button.tsx:6
```

**Comment by Roesh** [comment] 2021-05-19 14:53
When I got this error for my app, my workaround was similar to the manual redirect, but I didn't await the logout, and that seems to be working:

```
onClick={async () => {
              logoutMutation()
              router.push("/")
            }}
```

Is that a good idea? If so it could also be a workaround

**Comment by remjx** [comment] 2021-05-27 22:03
This doesn't address the root cause, but I think I prefer the following pattern over the previous mentioned workarounds:

Instead of triggering logout from the client side, create `pages/logout.tsx` that deletes the user session on the server then execute a server side redirect to homepage.

```
// app/pages/logout.tsx

const LogoutPage: BlitzPage = () => {
    return null
}

export default LogoutPage

export const getServerSideProps = async ({ req, res }) => {
    const session = await getSession(req, res)
    await session.$revoke()
    return {
        redirect: {
            destination: '/?logout-success=true',
            permanent: false,
        },
    }
}
```

This ensures the user session is revoked before any additional changes are triggered on the front end.

**Comment by flybayer** [comment] 2021-05-27 22:37
The `CancelledError` part of this is fixed in https://github.com/blitz-js/blitz/pull/2406. That fixes `.then` not working correctly and `router.push` not working right after a logout mutation.


Now I'm looking into the original issue of this thread which is `Page.authenticate.redirectTo` not working on logout with suspense.

**Comment by dangreaves** [comment] 2021-06-04 02:17
Just thought I would throw in my temporary solution to this for anyone experiencing the same problem with logout and suspense. Building upon the separate "logout" page solution which @remjx provided, I have instead put together an actual page which runs the mutation.

It does not redirect the user anywhere, rather just provides a "You have been logged out" message, which you could add a "Back to app" link or something into. By time the user clicks that link, the session will have been cleared and `Page.authenticate` etc will work as expected.

To logout from anywhere in the app, simply redirect to that page using `router.push(Routes.LogoutPage())` rather than running the logout mutation directly.

Create the below at `app/auth/pages/logout.tsx`. In my case, the `Modal` layout is just a trimmed down layout with a box in the middle, but you could use anything you like.

```tsx
import React from "react"
import { BlitzPage, useMutation } from "blitz"

import logout from "app/auth/mutations/logout"
import { Modal } from "app/core/layouts/Modal"

const LogoutPage: BlitzPage = () => {
  const [status, setStatus] = React.useState<"loading" | "complete">("loading")

  const [logoutMutation] = useMutation(logout)

  React.useEffect(() => {
    logoutMutation().finally(() => setStatus("complete"))
  }, [logoutMutation])

  if ("loading" === status) {
    return <div>Logging you out...</div>
  }

  return <div>You have been logged out.</div>
}

LogoutPage.getLayout = (page) => <Modal title="Logged out">{page}</Modal>

export default LogoutPage

```

**Comment by tafelito** [comment] 2021-06-07 22:42
@flybayer It seems like the client and the server sessions are not synced. In my case, when I logout, it triggers some other components to re-render and some queries to be executed (useCurrentUser and others The session on the client seems to be valid but when the server does `ctx.session.$authorize()` the session is already invalid and that causes an AuthorizationError

**Comment by flybayer** [comment] 2021-06-12 20:55
Ok folks, this should be fully resolved in the next release!

Some of you asked for a `redirectUnauthenticatedTo` feature. We already have that but it just hasn't worked correctly on logout.
```ts
Page.authenticate = {redirect: '/login'}
```

With the next release, if you use Page.authenticate.redirect, all you need to do is trigger a logout on that page and the user will be redirected correctly without you doing a manual redirect.

**Comment by tafelito** [comment] 2021-06-13 01:52
@flybayer What's the main use for  `redirectUnauthenticatedTo`? Is it the same as doing `Page.autheticate = true` or  `Page.authenticate = {redirect: '/login'}`?

The docs only mention `redirectAuthenticatedTo`

**Comment by dangreaves** [comment] 2021-06-13 02:03
@tafelito I think @flybayer means that `Page.authenticate` \*is\* the equivelant of a `redirectUnauthenticatedTo` feature. I searched the codebase and `redirectUnauthenticatedTo` doesn't actually exist.

**Comment by tafelito** [comment] 2021-06-13 02:51
That's what I thought, just wanted to double check he was referring to that. Thanks @dangreaves

**Closed** 2021-06-14 16:08 UTC
Labels: kind/bug, priority/high, status/assigned

**Comment by noxify** [comment] 2021-06-14 16:10
thanks @flybayer <3
