### ISSUE TITLE
Fix blitz internal dev issues with dependencies not building in correct order

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#595] opened 2020-05-31 14:20 UTC
### What is the problem?

We have a pretty rough situation with our blitz dev environment when running `yarn dev`.

When running `yarn build`, all packages are built in the proper order and everything works great. Dependent packages are automatically built before parent packages.

However, this does **not** work right with `yarn dev`. Everything is built in a random order resulting in errors like this:

```
@blitzjs/cli: src/commands/install.ts(3,25): error TS7016: Could not find a declaration file for module '@blitzjs/installer'. '/Users/b/c/blitz/packages/installer/dist/index.js' implicitly has an 'any' type.
@blitzjs/cli:   Try `npm install @types/blitzjs__installer` if it exists or add a new declaration (.d.ts) file containing `declare module '@blitzjs/installer';`
@blitzjs/cli: 8:58:46 PM - Found 1 error. Watching for file changes.
```

As a workaround thus far, we have package.json scripts like this to ensure packages are built in the proper order. But we're now adding more and more packages and it's getting out of hand.

```
    "predev": "wait-on ../core/dist/packages/core/src/index.d.ts && wait-on ../server/dist/packages/server/src/index.d.ts && wait-on ../generator/dist/packages/generator/src/index.d.ts && wait-on ../cli/lib/src/index.js",
```

### Steps to Reproduce

1. Remove all the `predev` package.json scripts
2. `yarn reset`
3. `yarn dev`

### Possible Fixes

1. Ideally we can fix this without all the `wait-on` stuff. I don't know if this is a lerna thing or a tsdx thing. I think maybe lerna? If so, maybe it's as simple as adding a certain configuration or cli flag. I don't know.
2. The other way is to write a custom node script that abstracts away the manual `wait-on` stuff. The node script can be called via a package.json script, and it would automatically detect the other blitz package dependencies and wait for those to be built.

**Comment by ivandevp** [comment] 2020-05-31 18:49
I can take a look at this 😃

**Comment by ryardley** [comment] 2020-05-31 22:17
Ha was thinking about this yesterday.

**Comment by flybayer** [comment] 2020-06-01 13:37
@ivandevp awesome! In the future, you can also assign yourself :)

**Comment by flybayer** [comment] 2020-06-19 02:23
@ivandevp have you made any progress on this? :)

**Comment by ivandevp** [comment] 2020-06-19 15:34
Oh sorry @flybayer ! I forgot completely about this issue and I was a bit full on my job. Let me retake it tomorrow please and sorry for forgetting about it.

**Comment by flybayer** [comment] 2020-06-20 03:37
@ivandevp ok no problem! :)

**Comment by ivandevp** [comment] 2020-06-22 16:33
Hey @flybayer! I've been trying to find a workaround for this and it seems that it's not a lerna issue. `lerna` by default runs on topological order unless we pass the `parallel` flag. The issue is that it runs the `watch` commands and keeps waiting for the previous package to get resolved in order to run the following in the deps graph and this doesn't happen. Not sure if someone has an idea to fix it with an existing tool before trying to create an script that handles this issue.

**Comment by flybayer** [comment] 2020-06-23 13:33
@ivandevp thank you for investigating!

Would changing to the following flow for `yarn dev` work?

1. Clean all dist folders (like currently do)
2. `lerna run build`
3. `lerna run dev`, but change package dev scripts from `tsdx watch` to `tsdx watch --noClean`

**Closed** 2021-01-22 22:35 UTC
Labels: kind/bad-experience, kind/meta, status/ready-to-work-on
