### ISSUE TITLE
Not obvious how to use Postgres for a new app

### ISSUE THREAD

**Issue by yhoiseth** [blitz-js/blitz#1000] opened 2020-09-03 13:58 UTC
### What do you want and why?

It is not obvious to me how to use Postgres when creating a new app. I want it to be easy.

### Possible implementation(s)

I don’t think I should suggest any solutions before I have properly described the problem.

### Additional context

Below is what I did and how I was confused. Consider it a usability test:

I start a new project with `blitz new test`.

I update `db/schema.prisma` by removing `"sqlite"` from `datasource db -> provider`. I also change `DATABASE_URL` in `.env.local`.

Then, I noticd an untracked directory and an untracked file:

- `db/migrations/20200903131827-initial-migration/`
- `db/migrations/migrate.lock`

It is not obvious to me what I should do with these. Are they still relevant, or should I delete them? I decide to keep them and run `blitz db migrate`. But then, I am asked for `Name of migration`. That can’t be right since I’m not actually writing a migration. So I press CTRL-C. Then, I get a lot of output and one more untracked file (`db/migrations/20200903134345/`).

I decide to delete all the untracked files. The only change I see on `git status` is now my modification of `db/schema.prisma`.

I then decide to run `blitz db migrate`. I get:

```
Error: There are more migrations in the database than locally. This must not happen.
Local migration ids: (empty).
Remote migration ids: 20200903131827-initial-migration, 20200903134345
```

So the last time I ran `migrate`, it both created and ran the migration? This is not what I expect coming from Rails and Django, where these things are a two-step process.

Anyway, let’s reset the database:

```
➜  test git:(master) ✗ blitz db reset
You are using alpha software - if you have any problems, please open an issue here:
    https://github.com/blitz-js/blitz/issues/new/choose

✔ Loading your database
✔ Are you sure you want to reset your database and erase ALL data? (y/N) · true
✕ Resetting the database has failed with an error from the database:
✕ Error:
Invalid `prisma.executeRaw()` invocation:


  Raw query failed. Code: `42704`. Message: `db error: ERROR: role "postgres" does not exist`
```

Huh, that’s weird. My `test` database may not be worth rescuing. I change it to `testdb` in `.env.local` and run `blitz db migrate`. That seems to work, but looking at my migrations, I don’t have the `[timestamp]-initial-migration/` directory that I had earlier.

At this point, I am thinking I probably overthought the entire thing and should probably just start over.

**Comment by flybayer** [comment] 2020-09-03 15:01
Sorry about that @yhoiseth! The initial untracked migration files is a bug (#968).

I did some investigation here, and the reason it created a new a migration file is because you changed the `provider` from `["sqlite", "postgres"]` to `"postgres"`. If you leave the provider as is and only change the DATABASE_URL, then it won't create a new migration. This is definitely confusing, and I've reported it to the Prisma team. Btw, prisma migrate which we are using here is still in experimental state. They are actively working on it right now to bring it to 1.0, and most likely this will be fixed.

So currently the happy path for switching to postgres is:

1. Change DATABASE_URL in `.env.local`
2. Run `blitz db migrate`.

> So the last time I ran migrate, it both created and ran the migration? This is not what I expect coming from Rails and Django, where these things are a two-step process.

Yes, Prisma migrations work a bit differently with Rails. With prisma, migrations are declarative. You change `schema.prisma` to be whatever you want, then run `blitz db migration` and it'll create a migration file for all your changes.

And if there are no changes to the schema file, `blitz db migrate` will run any pending migrations on the database without creating a new migration file.

**Comment by yhoiseth** [comment] 2020-09-04 05:58
@flybayer Thanks for clearing that up. I think it would be useful to have this information in the documentation. Should I give it a go?

**Comment by lukebennett** [comment] 2020-09-04 15:04
I don't know if this is the right place to flag this, but FYI the switch to defaulting `provider` to `["sqlite", "postgres"]` throws up issues when using enums in Prisma, you get a warning that the current provider doesn't support that data type (they are supported in postgres but not sqlite).

Appreciate this probably isn't a Blitz issue, most likely an editor one, or maybe a Prisma one, but given this has only just been [introduced to Blitz](https://github.com/blitz-js/blitz/commit/3433411a01029702c8834fb1669d0ce62a07e604), might want to consider either having a note in the docs about it, or reverting until the issue is fixed (if it ever is - might be intentional behaviour) so as to minimise any confusion?

On the subject of initial experience with postgres, I'm also getting constant errors due to a closed postgres connection which appears to be the result of #485 and the introduction of `useCurrentUser` in #916 (Blitz is trying to re-use a closed connection on every request). Would warrant its own issue, though I'm still digging into it - not sure if my database server is closing connections prematurely and exacerbating the problem

**Comment by lukebennett** [comment] 2020-09-04 16:08
Further to the above, some load balancer config was causing my database connections to close so the problem was mostly self-inflicted and I won't open an issue for it... perhaps one to keep in mind in case there are any other reports of similar experiences though, might still be some improvements to the new app experience warranted.

**Comment by aem** [comment] 2020-09-05 18:20
> Appreciate this probably isn't a Blitz issue, most likely an editor one, or maybe a Prisma one, but given this has only just been introduced to Blitz, might want to consider either having a note in the docs about it, or reverting until the issue is fixed (if it ever is - might be intentional behaviour) so as to minimise any confusion?

I think this is intentional - if `sqlite` is listed as a provider, all of your model code needs to support `sqlite`, so even though `pg` is listed you can only use the features that overlap with `sqlite` because Prisma has no way of knowing at compile time which DB you're going to be using with the client.

**Comment by yhoiseth** [comment] 2020-09-05 20:02
The ideal experience, I think, would be an option in `blitz new` to use Postgres as the database. The option could either be a flag (like the existing `--npm`) or an interactive option like the existing form library chooser.

The options could be

1. SQLite (the default); and
2. Postgres.

The choice determines which `DATABASE_URL` is set and which `datasource db -> provider` is set.

Other than the work involved, I can see one possible drawback: It might be more difficult to change database engine later. But I’m not sure about that.

**Comment by flybayer** [comment] 2020-09-08 01:12
@yhoiseth yeah you can go ahead and open a PR to improve the docs on this!

We are going to remove the `provider = ["sqlite", "postgres"]` thing because it's causing too many problems.

Instead, I think we should add a prompt to `blitz new` that asks if you want sqlite or postgres (same as we do now for form library). What do you all think about this?

**Comment by yhoiseth** [comment] 2020-09-08 06:27
> yeah you can go ahead and open a PR to improve the docs on this!

Will do :)

> We are going to remove the `provider = ["sqlite", "postgres"]` thing because it's causing too many problems.
> 
> Instead, I think we should add a prompt to `blitz new` that asks if you want sqlite or postgres (same as we do now for form library). What do you all think about this?

Yeah, that sounds great :)

**Closed** 2020-09-09 01:17 UTC
Labels: kind/bad-experience, status/in-review

**Comment by lukebennett** [comment] 2020-09-09 22:31
> I think this is intentional - if sqlite is listed as a provider, all of your model code needs to support sqlite, so even though pg is listed you can only use the features that overlap with sqlite because Prisma has no way of knowing at compile time which DB you're going to be using with the client.

This makes sense, I suspected that might be the case. It’s good to see the dual provider default is going though as it will simplify things.

> Instead, I think we should add a prompt to blitz new that asks if you want sqlite or postgres (same as we do now for form library). What do you all think about this?

This sounds perfect to me 👍🏻
