### ISSUE TITLE
Different behaviour for urls with and without trailing slash

### ISSUE THREAD

**Issue by donni106** [blitz-js/blitz#727] opened 2020-07-02 21:18 UTC
### What is the problem?

I found out, that I can acces the index page http://localhost:3000/projects but not the same page with a trailing slash http://localhost:3000/projects/, which results in a 404.
Similar with http://localhost:3000/projects/new everything is fine, but http://localhost:3000/projects/new/ results in an error.

### Steps to Reproduce

1. open `http://localhost:3000/projects` -> works fine
2. open `http://localhost:3000/projects/` -> not found
3. open `http://localhost:3000/projects/new` -> works fine
4. open  `http://localhost:3000/projects/new/` -> error

![Anmerkung 2020-07-02 231341](https://user-images.githubusercontent.com/1942953/86409696-ac112d80-bcb9-11ea-894b-48dbe8d66493.png)

### Versions

```
output of `blitz --version --verbose`
```

> Linux 4.4 | linux-x64 | Node: v14.3.0
>
> blitz: 0.16.0 (global)
> blitz: 0.16.0 (local)

### Other

There are inconsistancies across routes regarding trailing slashes. Some routes work with both versions, others not.
How should urls behave with and without trailing slashes in general?
Here is a blog post about the topic for further read: https://searchfacts.com/url-trailing-slash/
Found something next.js related here: https://stackoverflow.com/questions/57005120/how-can-you-handle-trailing-slashes-in-next-js-routes
In nextjs docs: https://nextjs.org/docs/api-reference/next.config.js/exportPathMap#adding-a-trailing-slash
Issue in nextjs repo: https://github.com/vercel/next.js/issues/5214

**Comment by flybayer** [comment] 2020-07-04 02:45
Thanks @donni106! I'm assuming this works fine with plain Next.js. And judging by the Prisma error, it looks like maybe there is a bug with our `useParam()` hook?

Someone just needs to dig into this a bit and find the root cause :)

**Comment by donni106** [comment] 2020-07-04 10:52
This is possible for the error with e.g. `.../projects/new/`.

But for the 404 on `.../projects/` I think it is something different. Have you checked the referenced issue in the nextjs repo? It is a long lasting discussion. There seems to be some difficulties also in plain nextjs.

**Comment by flybayer** [comment] 2020-07-04 10:56
Ok yeah I haven't dug into it. I'm currently focused on authentication, so hopefully someone else can look into this :)

**Comment by merelinguist** [comment] 2020-07-04 16:47
Yeah I think this is a Next problem, not a Blitz problem. In [this Next Sandbox](https://codesandbox.io/s/next-trailing-slash-demo-bnijd?file=/pages/users/%5Bid%5D.js), `users` resolves, as does `users/1`, but `users/` returns a `404`.

**Comment by merelinguist** [comment] 2020-07-04 16:47
Update: looks like it’s being fixed! https://github.com/vercel/next.js/issues/5214#issuecomment-648213750

**Comment by merelinguist** [comment] 2020-08-05 20:27
This has now been fixed in Next, so I’m closing this. If you see the Sandbox I linked above, I’ve updated Next to the latest version, and the routes now seem to work correctly. Please feel free to open again if this problem persists!

**Closed by merelinguist** 2020-08-05 20:27 UTC
Labels: kind/bug, needs investigation, status/ready-to-work-on
