### ISSUE TITLE
dev build fails randomly

### ISSUE THREAD

**Issue by sakulstra** [blitz-js/blitz#1543] opened 2020-11-27 19:00 UTC
### What is the problem?
For the fun of it I migrated a mostly client side next.js app(without a db) with a few getStaticProp fetching external data to blitz.js. 
Now almost 50% of my "save" actions result in:
```
Error: The default export is not a React Component in page: "/"
    at renderToHTML (../node_modules/next/dist/next-server/server/render.js:21:2377)
    at ../node_modules/next/dist/next-server/server/next-server.js:98:95
    at../node_modules/next/dist/next-server/server/next-server.js:91:148
    at DevServer.renderToHTMLWithComponents (../node_modules/next/dist/next-server/server/next-server.js:123:393)
    at DevServer.renderToHTML (../node_modules/next/dist/next-server/server/next-server.js:124:484)
    at async DevServer.renderToHTML (../node_modules/next/dist/server/next-dev-server.js:34:578)
    at async DevServer.render (../node_modules/next/dist/next-server/server/next-server.js:71:236)
    at async Object.fn (../node_modules/next/dist/next-server/server/next-server.js:55:618)
    at async Router.execute (../node_modules/next/dist/next-server/server/router.js:24:67)
    at async DevServer.run (../node_modules/next/dist/next-server/server/next-server.js:65:1023)
Error: The default export is not a React Component in page: "/"
```
on both the client and the server which i can only solve by saving the file once again.  don't really understand why this happens as   it's not a result of "broken dom", but also appears when altering a string :thinking: 

### Steps to Reproduce
I fear this reproduction might not work, as otherwise someone else would have reported this already :D
1. create a new blitz.js app
2. add tailwindcss recipe (i guess this can't be the problem?, will test if a can reproduce this on a vanilla app as well :thinking:)
3. try to develop & randomly face the issue reported above

The error happens for me on very basic pages as well:
```js
import { BlitzPage } from "blitz"
import Layout from "app/layouts/Layout"

const Home: BlitzPage = () => {
  return (
    <main className="container mx-auto justify-center items-center h-screen flex">
      <div className="w-full">
        <p className="text-center"></p>
        <div className="shadow w-full bg-grey-light rounded overflow-hidden ring-2 ring-blue-600 ring-offset-2 bg-blue-50 my-4 bg-blue-"></div>
      </div>
    </main>
  )
}

Home.getLayout = (page) => <Layout title="Home">{page}</Layout>

export default Home
```

### Versions

```
debug: blitzPkgPath: /home/lukass/Documents/aave/node_modules/blitz/dist/index.js
debug: cliPkgPath: /home/lukass/Documents/aave/node_modules/@blitzjs/cli/lib/src/index.js 

Linux 5.4 | linux-x64 | Node: v12.14.0

blitz: 0.26.0 (global)
blitz: 0.26.0 (local)

  Package manager: yarn 
  System:
    OS: Linux 5.4 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 6.96 GB / 15.52 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v12.14.0/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.12.1 => 2.12.1 
    @prisma/client: 2.12.1 => 2.12.1 
    blitz: 0.26.0 => 0.26.0 
    react: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530 
    react-dom: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530 
    typescript: 4.1.2 => 4.1.2 
```

### Other
![image](https://user-images.githubusercontent.com/4396533/100478122-82362880-30ea-11eb-8e3f-318881fb1eeb.png)

- might relate to https://github.com/blitz-js/blitz/issues/1509

**Comment by nitaking** [comment] 2020-12-01 00:38
@sakulstra 
Thanks for taking it up!

> i can only solve by saving the file once again. 

What does this mean?

**Comment by sakulstra** [comment] 2020-12-02 00:20
@nitaking pressing "ctrl + s" to manually save file.

https://www.awesomescreenshot.com/video/1918557?key=9b69a685878507e112ca41ff42c7d71f

**Comment by nitaking** [comment] 2020-12-03 11:43
@sakulstra 
Thank you reply. 
I haven't encountered it in my project (v0.23), so it may be a specific version issue.

**Comment by flybayer** [comment] 2020-12-05 23:59
This is a duplicate of #997, so closing in favor of that.

**Closed by flybayer** 2020-12-05 23:59 UTC
Labels: kind/bug, priority/high, status/ready-to-work-on
