### ISSUE TITLE
blitz install tailwind not working

### ISSUE THREAD

**Issue by Lucheti** [blitz-js/blitz#2794] opened 2021-10-03 21:28 UTC
### What is the problem?

when attempting to install tailwind recipe i get
"Cannot read property 'dots' of undefined"

### Paste all your error logs here:

```
blitz install tailwind

  ERROR  Cannot read property 'dots' of undefined

 .blitz/recipe-install/node_modules/ink-spinner/build/index.js:12:43

  9:  */
 10: const Spinner = ({ type = 'dots' }) => {
 11:     const [frame, setFrame] = react_1.useState(0);
 12:     const spinner = cli_spinners_1.default[type];
 13:     react_1.useEffect(() => {
 14:         const timer = setInterval(() => {
 15:             setFrame(previousFrame => {

 - Spinner (.blitz/recipe-install/node_modules/ink-spinner/build/index.js:12:43)
 - renderWithHooks (.blitz/recipe-install/node_modules/react-reconciler/cjs/react-reconciler.development.js:6036:18)
 -mountIndeterminateComponent 
                             (.blitz/recipe-install/node_modules/react-reconciler/cjs/react-reconciler.development.js:8570:13)

 - beginWork$1 (.blitz/recipe-install/node_modules/react-reconciler/cjs/react-reconciler.development.js:9938:16)
 -Object.invokeGuardedCallbackIm (.blitz/recipe-install/node_modules/react-reconciler/cjs/react-reconciler.development.js:1156
  l                             3:10)
 - invokeGuardedCallback (.blitz/recipe-install/node_modules/react-reconciler/cjs/react-reconciler.development.js:11740:31)
 - beginWork$$1 (.blitz/recipe-install/node_modules/react-reconciler/cjs/react-reconciler.development.js:15778:7)
 - performUnitOfWork (.blitz/recipe-install/node_modules/react-reconciler/cjs/react-reconciler.development.js:14696:12)
 - workLoopSync (.blitz/recipe-install/node_modules/react-reconciler/cjs/react-reconciler.development.js:14669:22)
 - performSyncWorkOnRoot (.blitz/recipe-install/node_modules/react-reconciler/cjs/react-reconciler.development.js:14265:11)

✕ TypeError: Cannot read property 'dots' of undefined
```

### Paste all relevant code snippets here:

```
blitz install tailwind
```

### What are detailed steps to reproduce this?

1. type "blitz install tailwind" in the cli

### Run `blitz -v` and paste the output here:

```
blitz -v
macOS Big Sur | darwin-x64 | Node: v12.22.1

blitz: 0.40.0 (global)
blitz: 0.40.0 (local)

  Package manager: npm 
  System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 26.38 GB / 64.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: Not Found
    npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 3.1.1 => 3.1.1 
    blitz: 0.40.0 => 0.40.0 
    prisma: 3.1.1 => 3.1.1 
    react: alpha => 18.0.0-alpha-bdd6d5064-20211001 
    react-dom: alpha => 18.0.0-alpha-bdd6d5064-20211001 
    typescript: ~4.3 => 4.3.5 
```

**Comment by beerose** [comment] 2021-10-04 08:13
Thanks for reporting. I'll close this issue in favor of this one: https://github.com/blitz-js/blitz/issues/2793 as the root cause is the same. Will continue the discussion there.

**Closed by beerose** 2021-10-04 08:13 UTC
Labels: kind/bug, status/triage
