### ISSUE TITLE
Allow selection of database and/or provider while scaffolding a new project 

### ISSUE THREAD

**Issue by thesobercoder** [blitz-js/blitz#1572] opened 2020-12-03 17:33 UTC
### What do you want and why?

Allowing selection of database and/or provider while scaffolding a new project would be great. Users can then select fauna/prisma prostgres/prisma mysql/dynamodb etc with a basic crud example will prevent users having to crawl through a million documentations.

PS - Absolutely love the concept of Blitz. Very excited to see what's in store, when it releases.

**Comment by MrLeebo** [comment] 2020-12-03 22:57
Thank you for the encouraging sentiment!

I believe this is a duplicate of https://github.com/blitz-js/blitz/issues/1037 and will be addressed by https://github.com/blitz-js/blitz/pull/1268 so I'm closing this issue but feel free to continue the discussion by following the links if you have anything else to add.

**Closed by MrLeebo** 2020-12-03 22:57 UTC
Labels: status/triage
