### ISSUE TITLE
Blitz install error in new javascript blitz project

### ISSUE THREAD

**Issue by mikeyXmomo** [blitz-js/blitz#3901] opened 2022-10-15 00:08 UTC
### What is the problem?

`blitz install material-ui `results in an error

Error appears with each package.

### Paste all your error logs here:

```
.blitz/recipe-install/index.ts:2:15 - error TS7016: Could not find a declaration file for module 'jscodeshift'. '/Users/macbookair/Documents/Projects/blitz-javascript/node_modules/jscodeshift/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/jscodeshift` if it exists or add a new declaration (.d.ts) file containing `declare module 'jscodeshift';`

2 import j from "jscodeshift"
                ~~~~~~~~~~~~~
.blitz/recipe-install/index.ts:78:57 - error TS7006: Parameter 'path' implicitly has an 'any' type.

78       program.find(j.ExportDefaultDeclaration).forEach((path) => {
                                                           ~~~~
.blitz/recipe-install/index.ts:112:18 - error TS7006: Parameter 'path' implicitly has an 'any' type.

112         .filter((path) => path.value?.id?.name === "App")
                     ~~~~
.blitz/recipe-install/index.ts:113:19 - error TS7006: Parameter 'path' implicitly has an 'any' type.

113         .forEach((path) => {
                      ~~~~
.blitz/recipe-install/index.ts:141:12 - error TS7006: Parameter 'path' implicitly has an 'any' type.

141           (path) =>
               ~~~~
.blitz/recipe-install/index.ts:145:19 - error TS7006: Parameter 'path' implicitly has an 'any' type.

145         .forEach((path) => {
                      ~~~~
```

### Paste all relevant code snippets here:

```
blitz install material-ui
```

### What are detailed steps to reproduce this?

1.Updated Blitz to version: 2.0.0-beta.12 with `sudo npm install -g blitz`
2. Created a new Blitz app with `blitz new`
3. Choose Javascript on "Pick a new project's language"
4. `cd` into folder
5. Attempted to install material-ui with `blitz install material-ui` and receiving the above error

### Run `blitz -v` and paste the output here:

```
blitz -v
Blitz version: 2.0.0-beta.12 (global)
Blitz version: 2.0.0-beta.12 (local)
macOS Monterey | darwin-arm64 | Node: v18.7.0


 Package manager: npm

  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 91.45 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 3.2.2 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.7.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.12 => 2.0.0-beta.12
    @blitzjs/next: 2.0.0-beta.12 => 2.0.0-beta.12
    @blitzjs/rpc: 2.0.0-beta.12 => 2.0.0-beta.12
    @prisma/client: 4.0.0 => 4.0.0
    blitz: 2.0.0-beta.12 => 2.0.0-beta.12
    next: 12.2.5 => 12.2.5
    prisma: 4.0.0 => 4.0.0
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.5.3 => 4.8.4
```

**Comment by beerose** [comment] 2022-10-17 07:44
Closing as a duplicate of https://github.com/blitz-js/blitz/issues/2470

Blitz recipes aren't currently supported for JS projects.

**Closed by beerose** 2022-10-17 07:44 UTC
Labels: kind/bug, status/triage
