### ISSUE TITLE
usePaginatedQuery loses type information if you destructure queryExtras

### ISSUE THREAD

**Issue by frankiesardo** [blitz-js/blitz#2671] opened 2021-08-26 13:51 UTC
### What is the problem?

When you use `usePaginatedQuery` the types are usually inferred correctly.

```ts
const [{ products }] = usePaginatedQuery(getQuestions, {...})
// The type of `products` is `Product[]`
```

But binding the `queryExtras` variable makes products lose its type info

```ts
const [{ products }, { refetch }] = usePaginatedQuery(getQuestions, {...})
// The type of `products` is `any`
```

What's funny is that if you don't destructure `products` and leave it as data, everything works again

```ts
const [data, { refetch }] = usePaginatedQuery(getQuestions, {...})
const { products } = data
// The type of `products` is `Product[]`
```

### Paste all relevant code snippets here:

```
const [{ products }] = usePaginatedQuery(getQuestions, {})
```

### What are detailed steps to reproduce this?

1. Start a new blitz project
2. Create a new model "product" with name:string
3. Modify the products/index.ts page with `const [{ products }, { refetch }] = usePaginatedQuery(getQuestions, {...})`
4. Check inferred type for `products`

### Run `blitz -v` and paste the output here:

```
macOS Mojave | darwin-x64 | Node: v14.17.5

blitz: 0.39.0 (global)
blitz: 0.39.0 (local)

  Package manager: yarn 
  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 1.08 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.30.0 => 2.30.0 
    blitz: 0.39.0 => 0.39.0 
    prisma: 2.30.0 => 2.30.0 
    react: alpha => 18.0.0-alpha-edfe50510-20210823 
    react-dom: alpha => 18.0.0-alpha-edfe50510-20210823 
    typescript: ~4.3 => 4.3.5 
```

**Comment by flybayer** [comment] 2021-08-30 22:53
Ah yeah, duplicate of #2609, so will close in favor of that. But thanks @frankiesardo!

**Closed by flybayer** 2021-08-30 22:53 UTC
Labels: kind/bug, status/triage
