### ISSUE TITLE
Heroku release command fails because `prisma` is not installed

### ISSUE THREAD

**Issue by thisdotrob** [blitz-js/blitz#2896] opened 2021-11-01 22:08 UTC
### What is the problem?

I have created a new app with `blitz new myApp` and followed the instructions at https://blitzjs.com/docs/deploy-heroku to deploy to heroku.

When running `blitz new` I selected `npm` for dependency management. I also set Node 16 in `engines` in `package.json` so that Heroku uses the same version as I am locally.

After pushing to Heroku the build succeeds but deploy fails because the release command errors.

Per the instructions, the release command is `npx blitz prisma migrate deploy`.

It looks like, when using `npm` at least, Heroku removes dev dependencies (including `prisma`) before the release command is run and Blitz doesn't know that it needs to install prisma if it is not present, so it bombs out.

I have reproduced this locally by clearing out `node_modules` and then running the above command.

### Paste all your error logs here:

```
    Error: Cannot find module 'prisma'
    Require stack:
    - /app/noop.js
    Code: MODULE_NOT_FOUND
```

### Paste all relevant code snippets here:

.

### What are detailed steps to reproduce this?

1. `blitz new appName`
2. Specify Node 16 in `package.json`'s `engines`.
2. Follow instructions at https://blitzjs.com/docs/deploy-heroku
3. `git push heroku main`

### Run `blitz -v` and paste the output here:

```
Linux 5.10 | linux-x64 | Node: v16.13.0

blitz: 0.41.1 (global)
blitz: 1.0.0 (local)

  Package manager: npm 
  System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 1.98 GB / 15.37 GB
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.15 - /usr/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

**Comment by beerose** [comment] 2021-11-03 14:21
It looks like the problem is with using `npx blitz`. I reproduced this issue with a different Prisma command. @flybayer any ideas?

**Comment by flybayer** [comment] 2021-11-06 16:35
Then issue is with this code here: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/prisma.ts#L4-L13

It should be changed to resolve `@blitzjs/server` from the current working directly, not relative to the file like it is now

**Comment by ganeshmani** [comment] 2021-11-20 11:32
I am facing this issue too. I need to deploy my app to the Heroku server Is anyone working on this issue?. @flybayer

**Comment by beerose** [comment] 2021-11-23 16:40
It looks like `devDependecies` weren't installed properly (and `prisma` is in dev deps). There are two options:

1. Install deps with `--production=false`, e.g. `npm --production=false install`. From the npm docs:

> With the --production flag (or when the NODE_ENV environment variable is set to production), npm will not install modules listed in devDependencies. To install all modules listed in both dependencies and devDependencies when NODE_ENV environment variable is set to production, you can use --production=false.

2. Move `prisma` from `devDependencies` to `dependecies`.

**Comment by beerose** [comment] 2021-12-15 14:06
Hi @thisdotrob, @ganeshmani. Did you solve the issue with the above suggestion?

**Comment by nsunami** [comment] 2022-05-24 11:53
> 2\. Move `prisma` from `devDependencies` to `dependecies`.

I was having the same issue and @beerose's second solution fixed the issue.

(Thank you, @beerose!)

**Comment by beerose** [comment] 2022-06-20 12:07
Closing this issue as it's fixed in toolkit app templates.

**Closed by beerose** 2022-06-20 12:07 UTC
Labels: kind/bug, status/ready-to-work-on
