### ISSUE TITLE
Getting blitz work with a monorepo setup

### ISSUE THREAD

**Issue by developer-rakeshpaul** [blitz-js/blitz#1410] opened 2020-11-04 02:26 UTC
### What is the problem?
Anyone got blitz running inside a mono repo.. I tried to setup a monorepo with both rushjs and Lerna with yarn workspaces.. getting following error with Lerna
```
Error: Cannot find module '/Users/johndoe/Workspace/projects/blitz-lerna/node_modules/date-fns/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:323:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:681:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:944:27)
    at Function._load (/Users/johndoe/Workspace/projects/blitz-lerna/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:112:42)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (/Users/johndoe/Workspace/projects/blitz-lerna/node_modules/@blitzjs/cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/johndoe/Workspace/projects/blitz-lerna/node_modules/@blitzjs/server/dist/server.cjs.development.js:39:15)
    at Module._compile (/Users/johndoe/Workspace/projects/blitz-lerna/node_modules/@blitzjs/cli/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/johndoe/Workspace/projects/blitz-lerna/node_modules/date-fns/package.json',
  requestPath: 'date-fns'
}
```
### Steps to Reproduce

1. Please clone the following repo https://github.com/developer-rakeshpaul/blitz-lerna.git

2. npx lerna bootstrap

3. try running blitz app using yarn start from packages/web folder

### Versions

```
output of `blitz --version --verbose`
macOS Catalina | darwin-x64 | Node: v12.16.3

blitz: 0.25.0-canary.1 (local)

  Package manager: npm
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 379.16 MB / 16.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.16.3 - ~/.config/nvm/12.16.3/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.config/nvm/12.16.3/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: Not Found
    @prisma/client: Not Found
    blitz: Not Found
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8
    typescript: Not Found
```

**Comment by flybayer** [comment] 2020-11-05 02:08
@developer-rakeshpaul looks like you forgot to push some commits to that repo (no blitz app in web). But I added a blitz app to the web folder myself to test, and it is working fine. I'm unable to reproduce your error.

**Comment by nitaking** [comment] 2020-11-05 02:11
I same with flybayer.

**Comment by developer-rakeshpaul** [comment] 2020-11-05 02:26
@flybayer @nitaking not sure what happened with the checkin. I am still facing the issue.. I have updated the packages with a newly created blitz app.. run `npx blitz new web` in the mono repo to create a new project I am still getting the same error

`Error: Cannot find module '/Users/johndoe/Workspace/projects/blitz-lerna/node_modules/date-fns/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:323:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:681:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:944:27)
    at Function._load (/Users/johndoe/Workspace/projects/blitz-lerna/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:112:42)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (/Users/johndoe/Workspace/projects/blitz-lerna/node_modules/@blitzjs/cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/johndoe/Workspace/projects/blitz-lerna/node_modules/@blitzjs/server/dist/server.cjs.development.js:39:15)
    at Module._compile (/Users/johndoe/Workspace/projects/blitz-lerna/node_modules/@blitzjs/cli/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/johndoe/Workspace/projects/blitz-lerna/node_modules/date-fns/package.json',
  requestPath: 'date-fns'
}`


```
debug: blitzPkgPath: /Users/johndoe/Workspace/projects/blitz-lerna/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/johndoe/Workspace/projects/blitz-lerna/node_modules/@blitzjs/cli/lib/src/index.js

macOS Catalina | darwin-x64 | Node: v12.16.3

blitz: 0.25.0-canary.1 (local)

  Package manager: npm
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 188.48 MB / 16.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.16.3 - ~/.config/nvm/12.16.3/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.config/nvm/12.16.3/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: Not Found
    @prisma/client: Not Found
    blitz: Not Found
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8
    typescript: 4.0.5 => 4.0.5
```

**Comment by flybayer** [comment] 2020-11-05 02:33
@developer-rakeshpaul do you have yarn installed?

**Comment by developer-rakeshpaul** [comment] 2020-11-05 02:40
@flybayer Yes I do

```
~/W/p/b/p/web (master | 👍 ) ❯❯❯ yarn --version
1.22.10
```
even tried reinstalling yarn for peace of mind 

if you look at npmPackages it shows blitz as not found.. is it because I don't have blitz installed globally.

**Comment by flybayer** [comment] 2020-11-05 02:56
I get the same "not found" for blitz (because npxenv doesn't work with monorepo apparently for version detection).

Not sure what to to tell you to try at this point 🤷

**Comment by developer-rakeshpaul** [comment] 2020-11-05 02:58
@flybayer how you got it working earlier?

**Comment by flybayer** [comment] 2020-11-05 03:02
@developer-rakeshpaul it just works fine for me, including what you have pushed up now.

**Comment by developer-rakeshpaul** [comment] 2020-11-05 03:06
@flybayer which node version are you using?

**Comment by flybayer** [comment] 2020-11-06 01:15
v12.16.1

**Comment by developer-rakeshpaul** [comment] 2020-11-06 03:18
@flybayer tried to run the same setup on my friends machine and he was getting  styled-jsx missing error... I couldn't grab the version info but there seems to be some inconsistency in the way it works with monorepos..

**Comment by flybayer** [comment] 2020-11-07 15:40
Ok seems theres some issues here. I marked as a bug and ready for someone to work on.

**Comment by rizkyramadhan** [comment] 2020-11-21 02:25
I am succesfully using blitzjs monorepo without lerna, and just using yarn 1 workspace. Following this tutorial: https://dev.to/t7yang/typescript-yarn-workspace-monorepo-1pao

Typescript just work across local package - you can get typings from another local package.

**Comment by markhughes** [comment] 2021-02-17 22:50
Lerna is typically used if you want to _deploy_ multiple packages from a single monorepo. If you don't want this, yarn workspaces is enough.

**Comment by niklasgrewe** [comment] 2021-04-21 16:12
@rizkyramadhan How do you get this working? When i run a new blitz app in `packages/web` i get the following runtime error: 

```
_blitzjs_core__WEBPACK_IMPORTED_MODULE_6__.Routes.SignupPage is not a function
```

**Comment by rizkyramadhan** [comment] 2021-04-21 17:00
Ermm.. that is year ago. Nowadays I am using customized esbuild without using any framework in my project.

**Comment by flybayer** [comment] 2021-04-24 20:31
@niklasgrewe can you open a new issue for that? Looks like a bug with our new Routes manifest feature.

**Comment by niklasgrewe** [comment] 2021-04-25 16:11
@flybayer done #2272

**Comment by flybayer** [comment] 2021-08-24 22:04
Should be working fine now

**Closed by flybayer** 2021-08-24 22:04 UTC
Labels: kind/bug, status/ready-to-work-on
